export const DEFAULT_INJURY_TYPES = [
  "Contusão (pisadura)",
  "Corte / laceração",
  "Perfuração",
  "Amputação (total ou parcial)",
  "Esmagamento",
  "Hematoma",
  "Abrasão / escoriação",
  "Fratura simples",
  "Fratura exposta",
  "Fratura múltipla",
  "Fissura óssea",
  "Luxação",
  "Subluxação",
  "Distensão muscular",
  "Rotura muscular",
  "Entorse",
  "Rotura de ligamentos",
  "Tendinite",
  "Tenossinovite",
  "Mialgia (dor muscular)",
  "Entorse articular",
  "Inflamação articular",
  "Limitação de movimentos",
  "Derrame articular",
  "Concussão cerebral",
  "Traumatismo cranioencefálico (TCE)",
  "Lesão nervosa periférica",
  "Dormência / parestesia",
  "Perda de consciência",
  "Vertigens pós-trauma",
  "Queimadura térmica",
  "Queimadura química",
  "Queimadura elétrica",
  "Dermatite de contacto",
  "Irritação cutânea",
  "Bolhas",
  "Corpo estranho no olho",
  "Irritação ocular",
  "Queimadura ocular",
  "Perda parcial ou total da visão",
  "Trauma acústico",
  "Perda auditiva temporária",
  "Perda auditiva permanente",
  "Dor no ouvido",
  "Lesão por esforços repetitivos (LER)",
  "Distúrbios músculo-esqueléticos relacionados com o trabalho (DORT)",
  "Síndrome do túnel cárpico",
  "Lombalgia",
  "Cervicalgia",
  "Hemorragia interna",
  "Lesão em órgãos internos",
  "Contusão torácica",
  "Traumatismo abdominal",
  "Intoxicação",
  "Asfixia",
  "Choque elétrico",
  "Golpe de calor",
  "Hipotermia",
  "Reação alérgica",
] as const;

