export const SYSTEM_PARAMETER_KEYS = {
  SLA: "SLA_CONFIG",
  ALERT: "ALERT_CONFIG",
  REPEATABILITY_ALERT: "REPEATABILITY_ALERT_CONFIG",
  GLOBAL_REPEATABILITY_ALERT: "GLOBAL_REPEATABILITY_ALERT_CONFIG",
  SAFETY_DAYS: "SAFETY_DAYS_CONFIG",
  MONTHLY_INPUTS_LAYOUT: "MONTHLY_INPUTS_LAYOUT",
  COMPETENCE_EXPIRING_THRESHOLD_DAYS: "COMPETENCE_EXPIRING_THRESHOLD_DAYS",
  AUTHORIZATION_SEGREGATION_OF_DUTIES: "AUTHORIZATION_SEGREGATION_OF_DUTIES",
  MEDICAL_FITNESS_BLOCKS_AUTHORIZATION: "MEDICAL_FITNESS_BLOCKS_AUTHORIZATION",
} as const;

/** §5/§2.1 of docs/modulo-competencias-autorizacoes.md. */
export const DEFAULT_COMPETENCE_EXPIRING_THRESHOLD_DAYS = 90;
export const DEFAULT_AUTHORIZATION_SEGREGATION_OF_DUTIES = true;
export const DEFAULT_MEDICAL_FITNESS_BLOCKS_AUTHORIZATION = false;

export const DEFAULT_SLA_DAYS = {
  LOW: 21,
  MEDIUM: 14,
  HIGH: 7,
} as const;

export const DEFAULT_ALERT_CONFIG = {
  windowDays: 30,
  nOccurrences: 3,
  consecutiveOccurrences: 3,
};

export const DEFAULT_REPEATABILITY_ALERT_CONFIG = {
  workerWeeklyLevel1Enabled: true,
  workerWeeklyLevel1Threshold: 2,
  workerWeeklyLevel2Enabled: true,
  workerWeeklyLevel2Threshold: 5,
  workstationNearMissWeeklyEnabled: true,
  workstationNearMissWeeklyThreshold: 1,
} as const;
