type WidenStrings<T> = {
  [Key in keyof T]: T[Key] extends string
    ? string
    : T[Key] extends Record<string, unknown>
      ? WidenStrings<T[Key]>
      : T[Key];
};

export const BASE_N0_MASTER_DATA_UI = {
  title: "Plant Master Data",
  helpButton: "Help",
  n0Admin: "N0 Admin",
  adminSettingsTitle: "Admin settings",
  settingsSectionTitle: "Settings",
  noPlantAvailable: "No plant available yet. Create the first plant above.",
  selectedPlantTitle: "Selected plant",
  defaultLanguage: "Default language",
  save: "Save",
  plantLanguageSaved: "Default language updated for {plant}.",
  plantLanguageError: "Failed to update plant language.",
  managePlants: "Manage plants",
  createPlant: "Create plant",
  backToCorporate: "Back to corporate",
  plantCode: "Plant code",
  plantName: "Plant name",
  timeZone: "Time zone",
  activePlant: "Active plant",
  n1Email: "N1 email",
  n1Name: "N1 name",
  n2Email: "N2 email",
  n2Name: "N2 name",
  n3Email: "N3 email",
  n3Name: "N3 name",
  inactive: "inactive",
  deletePlant: "Delete plant",
  plantSaved: "Plant and leadership roles saved.",
  plantUpdated: "Plant updated successfully.",
  plantDeleted: "Plant deleted successfully.",
  failedToSavePlant: "Failed to save plant.",
  failedToUpdatePlant: "Failed to update plant.",
  failedToDeletePlant: "Failed to delete plant.",
  deletePlantConfirm: "Delete plant \"{plant}\"? This removes plant-scoped data and roles.",
  generatedPasswords: "Generated passwords",
  moduleSettingsSaved: "Module settings saved.",
  moduleSettingsError: "Failed to save module settings.",
  globalModulesTitle: "Plant Modules",
  globalModulesHelp: "Activate or deactivate modules globally for all plants. Plant-specific settings can still override these defaults.",
  plantModulesTitle: "Plant Modules: {plant}",
  plantModulesHelp: "Activate or deactivate modules only for the selected plant.",
  saveGlobalModules: "Save global modules",
  savePlantModules: "Save plant modules",
  cancel: "Cancel",
  edit: "Edit",
  deactivate: "Deactivate",
  deactivateAll: "Deactivate all",
  updating: "Updating...",
  deactivatingAll: "Deactivating all...",
  saving: "Saving...",
  importExcel: "Import Excel",
  importingExcel: "Importing Excel...",
  downloadTemplate: "Export Excel",
  syncInjuryTypes: "Sync injury types",
  syncingInjuryTypes: "Syncing injury types...",
  loadPl01Defaults: "Load PL01 defaults",
  loadingPl01Defaults: "Loading PL01 data...",
  category: "Category",
  employeeNumber: "Employee number",
  workerName: "Worker name",
  department: "Department",
  saveWorker: "Save worker",
  saveChanges: "Save changes",
  noWorkers: "No workers registered.",
  workerSectionTitle: "Workers",
  workerEditMessage: "Editing worker \"{code}\".",
  itemEditMessage: "Editing {section} \"{code}\".",
  permissionDenied: "You do not have permission to edit data for this plant.",
  failedToSaveItem: "Failed to save {section}.",
  itemCreated: "{section} created successfully.",
  itemUpdated: "{section} updated successfully.",
  failedToUpdateItem: "Failed to update {section}.",
  failedToSaveWorker: "Failed to save worker.",
  failedToUpdateWorker: "Failed to update worker.",
  duplicateWorker: "A worker with this employee number already exists in this plant.",
  workerCreated: "Worker created successfully.",
  workerUpdated: "Worker updated successfully.",
  workerDeleteConfirm: "Deactivate this worker? It will stop appearing in new selections but remain in historical records.",
  workerDeleteSuccess: "Worker removed from active lists.",
  workerDeleteAllConfirm: "Deactivate all workers? They will stop appearing in new selections but remain in historical records.",
  workerDeleteAllSuccess: "All workers removed from active lists.",
  importError: "Failed to import Excel.",
  importSuccess: "Import completed: {departments} departments, {workstations} workstations, {equipments} equipment records and {workers} workers.",
  pl01Error: "Failed to load PL01 defaults.",
  pl01Success: "PL01 defaults loaded: {workstations} workstations, {workers} workers and {injuryTypes} injury types.",
  injurySyncError: "Failed to sync injury types.",
  injurySyncSuccess: "Injury type list synchronized for this plant: {injuryTypes} active options.",
  excelHelp:
    "Excel workbooks can include sheets named `Departments`, `Workstations`, `Equipment` and `Workers`. The downloaded workbook can be edited and re-imported; updates are matched by code or employee number inside the selected plant.",
  recipientListsHelp: "Recipient lists define who receives alerts and reports for this plant or corporate scope.",
  alertRulesHelp: "Alert rules define repeatability thresholds and the period used to trigger notifications.",
  noRecipientLists: "No recipient lists configured.",
  noAlertRules: "No alert rules configured.",
  sewoRecipients: {
    title: "Recipient List",
    help: "Manage the external recipients who should receive approved S-EWO reports. Each recipient receives the report in the selected language.",
    create: "Add recipient",
    edit: "Edit recipient",
    noRecipients: "No recipients configured for approved S-EWO reports.",
    savedCreated: "Recipient created successfully.",
    savedUpdated: "Recipient updated successfully.",
    saveError: "Failed to save recipient.",
    deleteConfirm: "Remove recipient \"{name}\"? They will stop receiving approved S-EWO reports.",
    deleteError: "Failed to remove recipient.",
    deleted: "Recipient removed successfully.",
    editing: "Editing recipient \"{name}\".",
  },
  safetyCommunicationRecipients: {
    title: "Safety Communication Alerts",
    help: "Configure which N4 supervisors receive automatic alerts for approved safety communications by department.",
    supervisorLabel: "Supervisor",
    departmentLabel: "Department",
    add: "Add recipient",
    saved: "Alert recipient saved.",
    saveError: "Failed to save alert recipient.",
    deleteConfirm: "Remove alert recipient \"{name}\" from department \"{department}\"?",
    deleteError: "Failed to remove alert recipient.",
    deleted: "Alert recipient removed successfully.",
    noRecipients: "No alert recipients configured.",
    noUsers: "No active N4 supervisors available for this plant.",
    noDepartments: "No departments available for this plant.",
  },
  safetyDays: {
    title: "Days without accidents",
    help:
      "Set the last accident date used by the Safety Dashboard and register a historical record from before this application existed.",
    lastAccidentDate: "Last accident date",
    historicalRecordDays: "Historical record days",
    recordStartDate: "Record start date",
    saved: "Days without accidents settings saved.",
    error: "Error saving Days without accidents settings.",
    saveSettings: "Save settings",
  },
  sla: {
    title: "SLA by Priority (days)",
    help: "Configure the default due date in days for actions created with low, medium or high priority.",
    low: "Low priority",
    medium: "Medium priority",
    high: "High priority",
    save: "Save SLA",
    saved: "SLA saved.",
    error: "Error saving SLA.",
  },
  qr: {
    title: "QR Token Manager",
    help: "Regenerate one token type at a time. The previous active token of the same type is revoked.",
    reportToken: "Report QR token",
    kioskToken: "Kiosk QR token",
    regenerate: "Regenerate {token}",
    regenerating: "Regenerating...",
    failedRegenerate: "Failed to regenerate token.",
    regenerated: "Token regenerated. Previous active token of this type was revoked.",
    linkCopied: "Link copied to clipboard.",
    printBlocked: "Unable to open print window. Check browser pop-up settings.",
    printFailed: "Could not start print automatically. Use the Print button in the opened window.",
    publicLink: "Public link",
    rawToken: "Raw token",
    copyLink: "Copy link",
    openLink: "Open link",
    saveImage: "Save image",
    printQr: "Print QR",
    print: "Print",
    printHint: "If auto-print does not start, click the button above.",
    qrAlt: "{type} QR code",
  },
  unsafeActManager: {
    help: "Configure the grouped options used when a communication is classified as Unsafe Act.",
    saved: "Unsafe act type saved.",
    removed: "Unsafe act type removed from active lists.",
    saveError: "Failed to save unsafe act type.",
    deleteError: "Failed to delete unsafe act type.",
    deleteConfirm: "Delete unsafe act type \"{name}\"? Existing communications keep their saved reference.",
    editing: "Editing {code}.",
    subcategoryOption: "Subcategory option",
    addType: "Add type",
  },
  users: {
    title: "User Management",
    email: "Email",
    fullName: "Full name",
    role: "Role",
    language: "Language",
    active: "Active",
    allRoles: "All roles",
    allStatus: "All status",
    activeStatus: "Active",
    inactiveStatus: "Inactive",
    created: "Created",
    updated: "Updated",
    actions: "Actions",
    yes: "Yes",
    no: "No",
    searchPlaceholder: "Search by name or email",
    newPasswordPlaceholder: "New password (optional)",
    passwordPlaceholder: "Password (optional, auto-generated if empty)",
    keepPasswordHelp: "Leave password empty to keep the current password.",
    generatedPasswordHelp:
      "Password is optional. If left empty, the system generates a temporary password, sends it by email, and requires password change at first login.",
    noPermission: "You do not have permission to create users in this plant.",
    createUser: "Create user",
    updateUser: "Update user",
    cancelEdit: "Cancel edit",
    delete: "Delete",
    activate: "Activate",
    deactivate: "Deactivate",
    sortCreatedDesc: "Created (newest first)",
    sortCreatedAsc: "Created (oldest first)",
    sortUpdatedDesc: "Updated (newest first)",
    sortUpdatedAsc: "Updated (oldest first)",
    sortNameAsc: "Name (A-Z)",
    sortNameDesc: "Name (Z-A)",
    loadError: "Failed to load users.",
    updateError: "Failed to update user.",
    deleteError: "Failed to delete user.",
    saveError: "Failed to save user.",
    unexpectedError: "Unexpected error.",
    updateStatusUnexpected: "Unexpected error while updating user status.",
    deleteUnexpected: "Unexpected error while deleting user.",
    saveUnexpected: "Unexpected error while saving user.",
    validationError: "Validation error",
    passwordMinLength: "Password must be at least 8 characters, or leave it empty to keep the current value.",
    deleteConfirm: "Delete user \"{name}\"?",
    userUpdated: "User updated",
    userUpdatedMessage: "User updated successfully.",
    userActivated: "User was activated successfully.",
    userDeactivated: "User was deactivated successfully.",
    userDeleted: "User deleted",
    userDeletedMessage: "User was deleted successfully.",
    userSaved: "User saved",
    tempPasswordEmailed: "Temporary password was sent by email and user must change it at first login.",
    emailDeliveryFailed: "Email delivery failed",
    emailDeliveryFailedMessage: "User saved, but email delivery failed. Share this temporary password securely: {password}",
    customPasswordSet: "User saved with the password informed in the form.",
    userSavedMessage: "User saved.",
  },
  professionalRisks: {
    eyebrow: "Professional Risks",
    title: "Professional risks configuration",
    help: "These categories and risks feed the grouped dropdown in safety communications and are stored with each report for HSE analysis.",
    syncDefaultList: "Sync default list",
    syncing: "Syncing...",
    editRisk: "Edit risk",
    createRisk: "Create risk",
    code: "Code",
    category: "Category",
    riskSubcategory: "Risk / subcategory",
    addRisk: "Add risk",
    saveRisk: "Save risk",
    noRisksTitle: "No professional risks configured yet.",
    noRisksHelp: "Use the default list or create categories manually.",
    activeCount: "{active} active / {total} risks",
    inactive: "Inactive",
    disable: "Disable",
    disabling: "Disabling...",
    activate: "Activate",
    activating: "Activating...",
    savedCreated: "Professional risk created.",
    savedUpdated: "Professional risk updated.",
    saveError: "Failed to save professional risk.",
    syncSuccess: "Default professional risks synchronized: {count} risks.",
    syncError: "Failed to sync default professional risks.",
    activateSuccess: "Professional risk activated.",
    activateError: "Failed to activate professional risk.",
    disableSuccess: "Professional risk disabled.",
    disableError: "Failed to disable professional risk.",
    disableConfirm: "Disable professional risk {code}? Existing communications will keep their selected value.",
    editing: "Editing {code}.",
  },
  reportLayout: {
    title: "Report Layout",
    help: "Configure the report sections and descriptions used by the plant report generator.",
    addLayout: "Add layout",
    layoutTitle: "Layout {index}",
    remove: "Remove",
    titlePlaceholder: "Layout title",
    descriptionPlaceholder: "Layout description / sections",
    saveLayouts: "Save layouts",
    saved: "Report layouts saved.",
    error: "Failed to save report layouts.",
  },
  help: {
    module:
      "Manage the master data used by the selected plant. Records created here are scoped to this plant and become available in communications, actions and related modules. Deactivating a record removes it from new selections but keeps historical references.",
    area:
      "Departments identify the organizational area linked to communications and reports. Codes must be unique inside the selected plant.",
    workstation:
      "Workstations identify the physical work location. The internal ID is preserved when you edit the code, so historical records remain linked.",
    equipment:
      "Equipment records are plant-specific assets that can be selected in communications. Use deactivation when a record has historical usage.",
    nearMissType:
      "Near miss types classify near miss communications. Codes stay technical; only the displayed name should describe the option for users.",
    unsafeActType:
      "Unsafe act types classify unsafe behavior. Categories group the dropdown options shown to users.",
    unsafeConditionType:
      "Unsafe condition types classify unsafe workplace conditions. Categories group the dropdown options shown to users.",
    injuryType:
      "Injury types define the nature of injury options used in first aid and accident records.",
    workers:
      "Workers are the plant employee directory used in communications, recurrence alerts and reports. Employee numbers must be unique inside the selected plant.",
  },
  sections: {
    area: {
      title: "Departments",
      codePlaceholder: "Department code",
      namePlaceholder: "Department name",
      createLabel: "Save department",
      emptyLabel: "No departments registered.",
      deleteConfirm: "Deactivate this department? It will stop appearing in new selections but remain in historical records.",
      deleteSuccess: "Department removed from active lists.",
      deleteAllConfirm: "Deactivate all departments? They will stop appearing in new selections but remain in historical records.",
      deleteAllSuccess: "All departments removed from active lists.",
      duplicateMessage: "A department with this code already exists in this plant.",
    },
    workstation: {
      title: "Workstations",
      codePlaceholder: "Workstation code",
      namePlaceholder: "Workstation name",
      createLabel: "Save workstation",
      emptyLabel: "No workstations registered.",
      deleteConfirm: "Deactivate this workstation? It will stop appearing in new selections but remain in historical records.",
      deleteSuccess: "Workstation removed from active lists.",
      deleteAllConfirm: "Deactivate all workstations? They will stop appearing in new selections but remain in historical records.",
      deleteAllSuccess: "All workstations removed from active lists.",
      duplicateMessage: "A workstation with this code already exists in this plant.",
    },
    equipment: {
      title: "Equipment",
      codePlaceholder: "Equipment code",
      namePlaceholder: "Equipment name",
      createLabel: "Save equipment",
      emptyLabel: "No equipment registered.",
      deleteConfirm: "Deactivate this equipment? It will stop appearing in new selections but remain in historical records.",
      deleteSuccess: "Equipment removed from active lists.",
      deleteAllConfirm: "Deactivate all equipment records? They will stop appearing in new selections but remain in historical records.",
      deleteAllSuccess: "All equipment records removed from active lists.",
      duplicateMessage: "Equipment with this code already exists in this plant.",
    },
    nearMissType: {
      title: "Near Miss Types",
      codePlaceholder: "Near miss code",
      namePlaceholder: "Near miss type name",
      createLabel: "Save near miss type",
      emptyLabel: "No near miss types registered.",
      deleteConfirm: "Deactivate this near miss type? It will stop appearing in new selections but remain in historical records.",
      deleteSuccess: "Near miss type removed from active lists.",
      deleteAllConfirm: "Deactivate all near miss types? They will stop appearing in new selections but remain in historical records.",
      deleteAllSuccess: "All near miss types removed from active lists.",
      duplicateMessage: "A near miss type with this code already exists in this plant.",
    },
    unsafeActType: {
      title: "Unsafe Act Types",
      codePlaceholder: "Unsafe act code",
      namePlaceholder: "Unsafe act option",
      createLabel: "Save unsafe act type",
      emptyLabel: "No unsafe act types registered.",
      deleteConfirm: "Deactivate this unsafe act type? It will stop appearing in new selections but remain in historical records.",
      deleteSuccess: "Unsafe act type removed from active lists.",
      deleteAllConfirm: "Deactivate all unsafe act types? They will stop appearing in new selections but remain in historical records.",
      deleteAllSuccess: "All unsafe act types removed from active lists.",
      duplicateMessage: "An unsafe act type with this code already exists in this plant.",
    },
    unsafeConditionType: {
      title: "Unsafe Condition Types",
      codePlaceholder: "Unsafe condition code",
      namePlaceholder: "Unsafe condition option",
      createLabel: "Save unsafe condition type",
      emptyLabel: "No unsafe condition types registered.",
      deleteConfirm: "Deactivate this unsafe condition type? It will stop appearing in new selections but remain in historical records.",
      deleteSuccess: "Unsafe condition type removed from active lists.",
      deleteAllConfirm: "Deactivate all unsafe condition types? They will stop appearing in new selections but remain in historical records.",
      deleteAllSuccess: "All unsafe condition types removed from active lists.",
      duplicateMessage: "An unsafe condition type with this code already exists in this plant.",
    },
    injuryType: {
      title: "Injury Types",
      codePlaceholder: "Injury type code",
      namePlaceholder: "Injury type name",
      createLabel: "Save injury type",
      emptyLabel: "No injury types registered.",
      deleteConfirm: "Deactivate this injury type? It will stop appearing in new selections but remain in historical records.",
      deleteSuccess: "Injury type removed from active lists.",
      deleteAllConfirm: "Deactivate all injury types? They will stop appearing in new selections but remain in historical records.",
      deleteAllSuccess: "All injury types removed from active lists.",
      duplicateMessage: "An injury type with this code already exists in this plant.",
    },
  },
} as const;

type DeepPartial<T> = {
  [Key in keyof T]?: T[Key] extends string
    ? string
    : T[Key] extends Record<string, unknown>
      ? DeepPartial<T[Key]>
      : T[Key];
};

const STATIC_N0_MASTER_DATA_UI: Record<string, DeepPartial<typeof BASE_N0_MASTER_DATA_UI>> = {
  pt: {
    title: "Master Data da Planta",
    helpButton: "Ajuda",
    n0Admin: "Admin N0",
    adminSettingsTitle: "Definições de administração",
    settingsSectionTitle: "Definições",
    noPlantAvailable: "Ainda não existe nenhuma planta. Crie a primeira planta acima.",
    selectedPlantTitle: "Planta selecionada",
    defaultLanguage: "Idioma padrão",
    save: "Guardar",
    plantLanguageSaved: "Idioma padrão atualizado para {plant}.",
    plantLanguageError: "Falha ao atualizar o idioma da planta.",
    managePlants: "Gerir plantas",
    createPlant: "Criar planta",
    backToCorporate: "Voltar ao corporate",
    plantCode: "Código da planta",
    plantName: "Nome da planta",
    timeZone: "Fuso horário",
    activePlant: "Planta ativa",
    n1Email: "Email N1",
    n1Name: "Nome N1",
    n2Email: "Email N2",
    n2Name: "Nome N2",
    n3Email: "Email N3",
    n3Name: "Nome N3",
    inactive: "inativa",
    deletePlant: "Eliminar planta",
    plantSaved: "Planta e perfis de liderança guardados.",
    plantUpdated: "Planta atualizada com sucesso.",
    plantDeleted: "Planta eliminada com sucesso.",
    failedToSavePlant: "Falha ao guardar a planta.",
    failedToUpdatePlant: "Falha ao atualizar a planta.",
    failedToDeletePlant: "Falha ao eliminar a planta.",
    deletePlantConfirm: "Eliminar a planta \"{plant}\"? Esta ação remove dados e perfis associados à planta.",
    generatedPasswords: "Passwords geradas",
    moduleSettingsSaved: "Definições dos módulos guardadas.",
    moduleSettingsError: "Falha ao guardar as definições dos módulos.",
    globalModulesTitle: "Módulos das plantas",
    globalModulesHelp: "Ative ou desative módulos globalmente para todas as plantas. As definições específicas da planta podem sobrepor estes valores.",
    plantModulesTitle: "Módulos da planta: {plant}",
    plantModulesHelp: "Ative ou desative módulos apenas para a planta selecionada.",
    saveGlobalModules: "Guardar módulos globais",
    savePlantModules: "Guardar módulos da planta",
    cancel: "Cancelar",
    edit: "Editar",
    deactivate: "Inativar",
    deactivateAll: "Inativar tudo",
    updating: "A atualizar...",
    deactivatingAll: "A inativar tudo...",
    saving: "A guardar...",
    importExcel: "Importar Excel",
    importingExcel: "A importar Excel...",
    downloadTemplate: "Exportar Excel",
    syncInjuryTypes: "Sincronizar tipos de lesão",
    syncingInjuryTypes: "A sincronizar tipos de lesão...",
    loadPl01Defaults: "Carregar dados PL01",
    loadingPl01Defaults: "A carregar dados PL01...",
    category: "Categoria",
    employeeNumber: "Número de trabalhador",
    workerName: "Nome do trabalhador",
    department: "Departamento",
    saveWorker: "Guardar trabalhador",
    saveChanges: "Guardar alterações",
    noWorkers: "Sem trabalhadores registados.",
    workerSectionTitle: "Trabalhadores",
    workerEditMessage: "A editar trabalhador \"{code}\".",
    itemEditMessage: "A editar {section} \"{code}\".",
    permissionDenied: "Não tem permissões para editar dados desta planta.",
    failedToSaveItem: "Falha ao guardar {section}.",
    itemCreated: "{section} criado com sucesso.",
    itemUpdated: "{section} atualizado com sucesso.",
    failedToUpdateItem: "Falha ao atualizar {section}.",
    failedToSaveWorker: "Falha ao guardar trabalhador.",
    failedToUpdateWorker: "Falha ao atualizar trabalhador.",
    duplicateWorker: "Já existe um trabalhador com este número nesta planta.",
    workerCreated: "Trabalhador criado com sucesso.",
    workerUpdated: "Trabalhador atualizado com sucesso.",
    workerDeleteConfirm: "Inativar este trabalhador? Deixa de aparecer em novas seleções, mas permanece no histórico.",
    workerDeleteSuccess: "Trabalhador removido das listas ativas.",
    workerDeleteAllConfirm: "Inativar todos os trabalhadores? Deixam de aparecer em novas seleções, mas permanecem no histórico.",
    workerDeleteAllSuccess: "Todos os trabalhadores foram removidos das listas ativas.",
    importError: "Falha ao importar Excel.",
    importSuccess: "Importação concluída: {departments} departamentos, {workstations} workstations, {equipments} equipamentos e {workers} trabalhadores.",
    pl01Error: "Falha ao carregar dados PL01.",
    pl01Success: "Dados PL01 carregados: {workstations} workstations, {workers} trabalhadores e {injuryTypes} tipos de lesão.",
    injurySyncError: "Falha ao sincronizar tipos de lesão.",
    injurySyncSuccess: "Lista de tipos de lesão sincronizada para esta planta: {injuryTypes} opções ativas.",
    excelHelp:
      "Os ficheiros Excel podem incluir folhas chamadas `Departments`, `Workstations`, `Equipment` e `Workers`. O ficheiro descarregado pode ser editado e importado novamente; as atualizações são associadas por código ou número de trabalhador dentro da planta selecionada.",
    recipientListsHelp: "As listas de destinatários definem quem recebe alertas e relatórios desta planta ou do âmbito corporate.",
    alertRulesHelp: "As regras de alerta definem limites de repetibilidade e o período usado para gerar notificações.",
    noRecipientLists: "Sem listas de destinatários configuradas.",
    noAlertRules: "Sem regras de alerta configuradas.",
    sewoRecipients: {
      title: "Lista de destinatarios",
      help: "Gira os destinatarios externos que devem receber os relatorios S-EWO aprovados. Cada destinatario recebe o relatorio no idioma definido.",
      create: "Adicionar destinatario",
      edit: "Editar destinatario",
      noRecipients: "Sem destinatarios configurados para relatorios S-EWO aprovados.",
      savedCreated: "Destinatario criado com sucesso.",
      savedUpdated: "Destinatario atualizado com sucesso.",
      saveError: "Falha ao guardar destinatario.",
      deleteConfirm: "Remover o destinatario \"{name}\"? Deixara de receber os relatorios S-EWO aprovados.",
      deleteError: "Falha ao remover destinatario.",
      deleted: "Destinatario removido com sucesso.",
      editing: "A editar destinatario \"{name}\".",
    },
    safetyCommunicationRecipients: {
      title: "Alertas de comunicacoes de seguranca",
      help: "Configure que supervisores N4 recebem alertas automaticos de comunicacoes de seguranca aprovadas por departamento.",
      supervisorLabel: "Supervisor",
      departmentLabel: "Departamento",
      add: "Adicionar destinatario",
      saved: "Destinatario de alerta guardado com sucesso.",
      saveError: "Falha ao guardar destinatario de alerta.",
      deleteConfirm: "Remover o destinatario \"{name}\" do departamento \"{department}\"?",
      deleteError: "Falha ao remover destinatario de alerta.",
      deleted: "Destinatario de alerta removido com sucesso.",
      noRecipients: "Sem destinatarios de alerta configurados.",
      noUsers: "Nao existem supervisores N4 ativos disponiveis para esta planta.",
      noDepartments: "Nao existem departamentos disponiveis para esta planta.",
    },
    safetyDays: {
      title: "Dias sem acidentes",
      help: "Defina a data do último acidente usada no Dashboard de Segurança e registe um recorde histórico anterior à existência desta aplicação.",
      lastAccidentDate: "Data do último acidente",
      historicalRecordDays: "Dias do recorde histórico",
      recordStartDate: "Data de início do recorde",
      saved: "Definições de dias sem acidentes guardadas.",
      error: "Erro ao guardar definições de dias sem acidentes.",
      saveSettings: "Guardar definições",
    },
    sla: {
      title: "SLA por prioridade (dias)",
      help: "Configure o prazo padrão em dias para ações criadas com prioridade baixa, média ou alta.",
      low: "Prioridade baixa",
      medium: "Prioridade média",
      high: "Prioridade alta",
      save: "Guardar SLA",
      saved: "SLA guardado.",
      error: "Erro ao guardar SLA.",
    },
    qr: {
      title: "Gestão de tokens QR",
      help: "Regere um tipo de token de cada vez. O token ativo anterior do mesmo tipo é revogado.",
      reportToken: "Token QR de reporte",
      kioskToken: "Token QR de quiosque",
      regenerate: "Regenerar {token}",
      regenerating: "A regenerar...",
      failedRegenerate: "Falha ao regenerar token.",
      regenerated: "Token regenerado. O token ativo anterior deste tipo foi revogado.",
      linkCopied: "Link copiado para a área de transferência.",
      printBlocked: "Não foi possível abrir a janela de impressão. Verifique as definições de pop-ups do browser.",
      printFailed: "Não foi possível iniciar a impressão automaticamente. Use o botão Imprimir na janela aberta.",
      publicLink: "Link público",
      rawToken: "Token bruto",
      copyLink: "Copiar link",
      openLink: "Abrir link",
      saveImage: "Guardar imagem",
      printQr: "Imprimir QR",
      print: "Imprimir",
      printHint: "Se a impressão automática não iniciar, clique no botão acima.",
      qrAlt: "Código QR {type}",
    },
    unsafeActManager: {
      help: "Configure as opções agrupadas usadas quando uma comunicação é classificada como ato inseguro.",
      saved: "Tipo de ato inseguro guardado.",
      removed: "Tipo de ato inseguro removido das listas ativas.",
      saveError: "Falha ao guardar tipo de ato inseguro.",
      deleteError: "Falha ao eliminar tipo de ato inseguro.",
      deleteConfirm: "Eliminar tipo de ato inseguro \"{name}\"? As comunicações existentes mantêm a referência guardada.",
      editing: "A editar {code}.",
      subcategoryOption: "Opção de subcategoria",
      addType: "Adicionar tipo",
    },
    users: {
      title: "Gestão de utilizadores",
      email: "Email",
      fullName: "Nome completo",
      role: "Perfil",
      language: "Idioma",
      active: "Ativo",
      allRoles: "Todos os perfis",
      allStatus: "Todos os estados",
      activeStatus: "Ativo",
      inactiveStatus: "Inativo",
      created: "Criado",
      updated: "Atualizado",
      actions: "Ações",
      yes: "Sim",
      no: "Não",
      searchPlaceholder: "Pesquisar por nome ou email",
      newPasswordPlaceholder: "Nova password (opcional)",
      passwordPlaceholder: "Password (opcional, gerada automaticamente se ficar vazia)",
      keepPasswordHelp: "Deixe a password vazia para manter a atual.",
      generatedPasswordHelp:
        "A password é opcional. Se ficar vazia, o sistema gera uma password temporária, envia-a por email e obriga a alteração no primeiro login.",
      noPermission: "Não tem permissões para criar utilizadores nesta planta.",
      createUser: "Criar utilizador",
      updateUser: "Atualizar utilizador",
      cancelEdit: "Cancelar edição",
      delete: "Eliminar",
      activate: "Ativar",
      deactivate: "Inativar",
      sortCreatedDesc: "Criado (mais recente primeiro)",
      sortCreatedAsc: "Criado (mais antigo primeiro)",
      sortUpdatedDesc: "Atualizado (mais recente primeiro)",
      sortUpdatedAsc: "Atualizado (mais antigo primeiro)",
      sortNameAsc: "Nome (A-Z)",
      sortNameDesc: "Nome (Z-A)",
      loadError: "Falha ao carregar utilizadores.",
      updateError: "Falha ao atualizar utilizador.",
      deleteError: "Falha ao eliminar utilizador.",
      saveError: "Falha ao guardar utilizador.",
      unexpectedError: "Erro inesperado.",
      updateStatusUnexpected: "Erro inesperado ao atualizar estado do utilizador.",
      deleteUnexpected: "Erro inesperado ao eliminar utilizador.",
      saveUnexpected: "Erro inesperado ao guardar utilizador.",
      validationError: "Erro de validação",
      passwordMinLength: "A password deve ter pelo menos 8 caracteres, ou ficar vazia para manter a atual.",
      deleteConfirm: "Eliminar utilizador \"{name}\"?",
      userUpdated: "Utilizador atualizado",
      userUpdatedMessage: "Utilizador atualizado com sucesso.",
      userActivated: "Utilizador ativado com sucesso.",
      userDeactivated: "Utilizador inativado com sucesso.",
      userDeleted: "Utilizador eliminado",
      userDeletedMessage: "Utilizador eliminado com sucesso.",
      userSaved: "Utilizador guardado",
      tempPasswordEmailed: "A password temporária foi enviada por email e o utilizador deve alterá-la no primeiro login.",
      emailDeliveryFailed: "Falha no envio do email",
      emailDeliveryFailedMessage: "Utilizador guardado, mas o envio do email falhou. Partilhe esta password temporária de forma segura: {password}",
      customPasswordSet: "Utilizador guardado com a password indicada no formulário.",
      userSavedMessage: "Utilizador guardado.",
    },
    professionalRisks: {
      eyebrow: "Riscos profissionais",
      title: "Configuração de riscos profissionais",
      help: "Estas categorias e riscos alimentam a dropdown agrupada das comunicações de segurança e ficam guardados em cada reporte para análise HSE.",
      syncDefaultList: "Sincronizar lista padrão",
      syncing: "A sincronizar...",
      editRisk: "Editar risco",
      createRisk: "Criar risco",
      code: "Código",
      category: "Categoria",
      riskSubcategory: "Risco / subcategoria",
      addRisk: "Adicionar risco",
      saveRisk: "Guardar risco",
      noRisksTitle: "Ainda não existem riscos profissionais configurados.",
      noRisksHelp: "Use a lista padrão ou crie categorias manualmente.",
      activeCount: "{active} ativos / {total} riscos",
      inactive: "Inativo",
      disable: "Inativar",
      disabling: "A inativar...",
      activate: "Ativar",
      activating: "A ativar...",
      savedCreated: "Risco profissional criado.",
      savedUpdated: "Risco profissional atualizado.",
      saveError: "Falha ao guardar risco profissional.",
      syncSuccess: "Riscos profissionais padrão sincronizados: {count} riscos.",
      syncError: "Falha ao sincronizar riscos profissionais padrão.",
      activateSuccess: "Risco profissional ativado.",
      activateError: "Falha ao ativar risco profissional.",
      disableSuccess: "Risco profissional inativado.",
      disableError: "Falha ao inativar risco profissional.",
      disableConfirm: "Inativar risco profissional {code}? As comunicações existentes mantêm o valor selecionado.",
      editing: "A editar {code}.",
    },
    reportLayout: {
      title: "Layout do relatório",
      help: "Configure as secções e descrições usadas pelo gerador de relatórios da planta.",
      addLayout: "Adicionar layout",
      layoutTitle: "Layout {index}",
      remove: "Remover",
      titlePlaceholder: "Título do layout",
      descriptionPlaceholder: "Descrição / secções do layout",
      saveLayouts: "Guardar layouts",
      saved: "Layouts de relatório guardados.",
      error: "Falha ao guardar layouts de relatório.",
    },
    help: {
      module:
        "Gira os dados mestre usados pela planta selecionada. Os registos criados aqui pertencem a esta planta e ficam disponíveis em comunicações, ações e módulos relacionados. Inativar um registo remove-o de novas seleções, mas mantém referências históricas.",
      area: "Os departamentos identificam a área organizacional associada a comunicações e relatórios. Os códigos devem ser únicos dentro da planta selecionada.",
      workstation:
        "As workstations identificam o local físico de trabalho. O ID interno é preservado quando edita o código, mantendo os registos históricos ligados.",
      equipment:
        "Os equipamentos são ativos específicos da planta que podem ser selecionados em comunicações. Use inativação quando existir histórico associado.",
      nearMissType:
        "Os tipos de quase acidente classificam comunicações de near miss. Os códigos permanecem técnicos; apenas o nome apresentado deve descrever a opção para os utilizadores.",
      unsafeActType:
        "Os tipos de ato inseguro classificam comportamentos inseguros. As categorias agrupam as opções apresentadas aos utilizadores.",
      unsafeConditionType:
        "Os tipos de condição perigosa classificam condições inseguras no local de trabalho. As categorias agrupam as opções apresentadas aos utilizadores.",
      injuryType: "Os tipos de lesão definem as opções de natureza de lesão usadas em primeiros socorros e acidentes.",
      workers:
        "Os trabalhadores são o diretório da planta usado em comunicações, alertas de recorrência e relatórios. Os números de trabalhador devem ser únicos dentro da planta.",
    },
    sections: {
      area: {
        title: "Departamentos",
        codePlaceholder: "Código do departamento",
        namePlaceholder: "Nome do departamento",
        createLabel: "Guardar departamento",
        emptyLabel: "Sem departamentos registados.",
        deleteConfirm: "Inativar este departamento? Deixa de aparecer em novas seleções, mas permanece no histórico.",
        deleteSuccess: "Departamento removido das listas ativas.",
        deleteAllConfirm: "Inativar todos os departamentos? Deixam de aparecer em novas seleções, mas permanecem no histórico.",
        deleteAllSuccess: "Todos os departamentos foram removidos das listas ativas.",
        duplicateMessage: "Já existe um departamento com este código nesta planta.",
      },
      workstation: {
        title: "Workstations",
        codePlaceholder: "Código da workstation",
        namePlaceholder: "Nome da workstation",
        createLabel: "Guardar workstation",
        emptyLabel: "Sem workstations registadas.",
        deleteConfirm: "Inativar esta workstation? Deixa de aparecer em novas seleções, mas permanece no histórico.",
        deleteSuccess: "Workstation removida das listas ativas.",
        deleteAllConfirm: "Inativar todas as workstations? Deixam de aparecer em novas seleções, mas permanecem no histórico.",
        deleteAllSuccess: "Todas as workstations foram removidas das listas ativas.",
        duplicateMessage: "Já existe uma workstation com este código nesta planta.",
      },
      equipment: {
        title: "Equipamentos",
        codePlaceholder: "Código do equipamento",
        namePlaceholder: "Nome do equipamento",
        createLabel: "Guardar equipamento",
        emptyLabel: "Sem equipamentos registados.",
        deleteConfirm: "Inativar este equipamento? Deixa de aparecer em novas seleções, mas permanece no histórico.",
        deleteSuccess: "Equipamento removido das listas ativas.",
        deleteAllConfirm: "Inativar todos os equipamentos? Deixam de aparecer em novas seleções, mas permanecem no histórico.",
        deleteAllSuccess: "Todos os equipamentos foram removidos das listas ativas.",
        duplicateMessage: "Já existe um equipamento com este código nesta planta.",
      },
      nearMissType: {
        title: "Tipos de Near Miss",
        codePlaceholder: "Código do near miss",
        namePlaceholder: "Nome do tipo de near miss",
        createLabel: "Guardar tipo de near miss",
        emptyLabel: "Sem tipos de near miss registados.",
        deleteConfirm: "Inativar este tipo de near miss? Deixa de aparecer em novas seleções, mas permanece no histórico.",
        deleteSuccess: "Tipo de near miss removido das listas ativas.",
        deleteAllConfirm: "Inativar todos os tipos de near miss? Deixam de aparecer em novas seleções, mas permanecem no histórico.",
        deleteAllSuccess: "Todos os tipos de near miss foram removidos das listas ativas.",
        duplicateMessage: "Já existe um tipo de near miss com este código nesta planta.",
      },
      unsafeActType: {
        title: "Tipos de Atos Inseguros",
        codePlaceholder: "Código do ato inseguro",
        namePlaceholder: "Opção de ato inseguro",
        createLabel: "Guardar tipo de ato inseguro",
        emptyLabel: "Sem tipos de ato inseguro registados.",
        deleteConfirm: "Inativar este tipo de ato inseguro? Deixa de aparecer em novas seleções, mas permanece no histórico.",
        deleteSuccess: "Tipo de ato inseguro removido das listas ativas.",
        deleteAllConfirm: "Inativar todos os tipos de ato inseguro? Deixam de aparecer em novas seleções, mas permanecem no histórico.",
        deleteAllSuccess: "Todos os tipos de ato inseguro foram removidos das listas ativas.",
        duplicateMessage: "Já existe um tipo de ato inseguro com este código nesta planta.",
      },
      unsafeConditionType: {
        title: "Tipos de Condições Perigosas",
        codePlaceholder: "Código da condição perigosa",
        namePlaceholder: "Opção de condição perigosa",
        createLabel: "Guardar tipo de condição perigosa",
        emptyLabel: "Sem tipos de condição perigosa registados.",
        deleteConfirm: "Inativar este tipo de condição perigosa? Deixa de aparecer em novas seleções, mas permanece no histórico.",
        deleteSuccess: "Tipo de condição perigosa removido das listas ativas.",
        deleteAllConfirm: "Inativar todos os tipos de condição perigosa? Deixam de aparecer em novas seleções, mas permanecem no histórico.",
        deleteAllSuccess: "Todos os tipos de condição perigosa foram removidos das listas ativas.",
        duplicateMessage: "Já existe um tipo de condição perigosa com este código nesta planta.",
      },
      injuryType: {
        title: "Tipos de Lesão",
        codePlaceholder: "Código do tipo de lesão",
        namePlaceholder: "Nome do tipo de lesão",
        createLabel: "Guardar tipo de lesão",
        emptyLabel: "Sem tipos de lesão registados.",
        deleteConfirm: "Inativar este tipo de lesão? Deixa de aparecer em novas seleções, mas permanece no histórico.",
        deleteSuccess: "Tipo de lesão removido das listas ativas.",
        deleteAllConfirm: "Inativar todos os tipos de lesão? Deixam de aparecer em novas seleções, mas permanecem no histórico.",
        deleteAllSuccess: "Todos os tipos de lesão foram removidos das listas ativas.",
        duplicateMessage: "Já existe um tipo de lesão com este código nesta planta.",
      },
    },
  },
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function mergeDeep<T>(base: T, override: unknown): T {
  if (!isRecord(base)) return (override ?? base) as T;
  if (!isRecord(override)) return base;

  const result: Record<string, unknown> = { ...base };
  for (const [key, value] of Object.entries(override)) {
    result[key] = isRecord(value) && isRecord(result[key]) ? mergeDeep(result[key], value) : value;
  }

  return result as T;
}

export type N0MasterDataUi = WidenStrings<typeof BASE_N0_MASTER_DATA_UI>;

export function formatMasterDataMessage(template: string, replacements: Record<string, string | number>) {
  return Object.entries(replacements).reduce(
    (message, [key, value]) => message.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

export function getStaticN0MasterDataUi(locale: string): N0MasterDataUi {
  return mergeDeep(BASE_N0_MASTER_DATA_UI, STATIC_N0_MASTER_DATA_UI[locale]);
}
