type SupportedReportLocale = "pt" | "it" | "en" | "pl" | "de" | "ro" | "fr";

type ReportText = {
  title: string;
  intro: string;
  type: string;
  typeUnsafeAct: string;
  typeUnsafeCondition: string;
  typeNearMiss: string;
  typeFirstAid: string;
  dateTime: string;
  reporterName: string;
  reporterNameNoNumbers: string;
  reporterNumber: string;
  department: string;
  selectDepartment: string;
  location: string;
  selectLocation: string;
  professionalRisk: string;
  selectProfessionalRisk: string;
  nearMissType: string;
  selectNearMissType: string;
  unsafeActType: string;
  selectUnsafeActType: string;
  shift: string;
  selectShift: string;
  involvedWorker: string;
  selectInvolvedWorker: string;
  natureOfInjury: string;
  selectNature: string;
  bodyPartAffected: string;
  selectBodyPart: string;
  description: string;
  suggestedAction: string;
  submit: string;
  submitSuccess: string;
  submitFailed: string;
};

const REPORT_TEXTS: Record<SupportedReportLocale, ReportText> = {
  en: {
    title: "Plant Safety Report",
    intro: "Unsafe Act, Unsafe Condition, Near Miss and First Aid follow the same mandatory logic as the software communication flow.",
    type: "Type",
    typeUnsafeAct: "Unsafe Act",
    typeUnsafeCondition: "Unsafe Condition",
    typeNearMiss: "Near Miss",
    typeFirstAid: "First Aid",
    dateTime: "Date and time",
    reporterName: "Reporter name",
    reporterNameNoNumbers: "Reporter name cannot contain numbers",
    reporterNumber: "Reporter number",
    department: "Department",
    selectDepartment: "Select department",
    location: "Location",
    selectLocation: "Select location",
    professionalRisk: "Professional risk",
    selectProfessionalRisk: "Select professional risk",
    nearMissType: "Near miss type",
    selectNearMissType: "Select near miss type",
    unsafeActType: "Unsafe act type",
    selectUnsafeActType: "Select unsafe act type",
    shift: "Shift",
    selectShift: "Select shift",
    involvedWorker: "Involved worker",
    selectInvolvedWorker: "Select involved worker",
    natureOfInjury: "Nature of injury",
    selectNature: "Select nature of injury",
    bodyPartAffected: "Body part affected",
    selectBodyPart: "Select body part",
    description: "Description",
    suggestedAction: "Suggested action",
    submit: "Submit communication",
    submitSuccess: "Communication submitted successfully.",
    submitFailed: "Submission failed",
  },
  pt: {
    title: "Relatório de Segurança da Fábrica",
    intro: "Ato inseguro, condição insegura, quase acidente e primeiros socorros seguem a mesma lógica obrigatória do fluxo de comunicação do software.",
    type: "Tipo",
    typeUnsafeAct: "Ato inseguro",
    typeUnsafeCondition: "Condição insegura",
    typeNearMiss: "Quase acidente",
    typeFirstAid: "Primeiros socorros",
    dateTime: "Data e hora",
    reporterName: "Nome do comunicante",
    reporterNameNoNumbers: "O nome do comunicante nao pode conter numeros",
    reporterNumber: "Número do comunicante",
    department: "Departamento",
    selectDepartment: "Selecionar departamento",
    location: "Local",
    selectLocation: "Selecionar local",
    professionalRisk: "Risco profissional",
    selectProfessionalRisk: "Selecionar risco profissional",
    nearMissType: "Tipo de Near Miss",
    selectNearMissType: "Selecionar tipo de Near Miss",
    unsafeActType: "Tipo de ato inseguro",
    selectUnsafeActType: "Selecionar tipo de ato inseguro",
    shift: "Turno",
    selectShift: "Selecionar turno",
    involvedWorker: "Trabalhador envolvido",
    selectInvolvedWorker: "Selecionar trabalhador envolvido",
    natureOfInjury: "Natureza da lesão",
    selectNature: "Selecionar natureza da lesão",
    bodyPartAffected: "Parte do corpo afetada",
    selectBodyPart: "Selecionar parte do corpo",
    description: "Descrição",
    suggestedAction: "Ação sugerida",
    submit: "Submeter comunicação",
    submitSuccess: "Comunicação submetida com sucesso.",
    submitFailed: "Falha no envio",
  },
  it: {
    title: "Segnalazione di Sicurezza dello Stabilimento",
    intro: "Atto insicuro, condizione insicura, near miss e primo soccorso seguono la stessa logica obbligatoria del flusso comunicazioni del software.",
    type: "Tipo",
    typeUnsafeAct: "Atto insicuro",
    typeUnsafeCondition: "Condizione insicura",
    typeNearMiss: "Near miss",
    typeFirstAid: "Primo soccorso",
    dateTime: "Data e ora",
    reporterName: "Nome del segnalatore",
    reporterNameNoNumbers: "Il nome del segnalatore non puo contenere numeri",
    reporterNumber: "Numero del segnalatore",
    department: "Reparto",
    selectDepartment: "Seleziona reparto",
    location: "Luogo",
    selectLocation: "Seleziona luogo",
    professionalRisk: "Rischio professionale",
    selectProfessionalRisk: "Seleziona rischio professionale",
    nearMissType: "Tipo di near miss",
    selectNearMissType: "Seleziona tipo di near miss",
    unsafeActType: "Tipo di atto insicuro",
    selectUnsafeActType: "Seleziona tipo di atto insicuro",
    shift: "Turno",
    selectShift: "Seleziona turno",
    involvedWorker: "Lavoratore coinvolto",
    selectInvolvedWorker: "Seleziona lavoratore coinvolto",
    natureOfInjury: "Natura della lesione",
    selectNature: "Seleziona natura della lesione",
    bodyPartAffected: "Parte del corpo interessata",
    selectBodyPart: "Seleziona parte del corpo",
    description: "Descrizione",
    suggestedAction: "Azione suggerita",
    submit: "Invia comunicazione",
    submitSuccess: "Comunicazione inviata con successo.",
    submitFailed: "Invio non riuscito",
  },
  pl: {
    title: "Raport Bezpieczenstwa Zakladu",
    intro: "Niebezpieczne zachowanie, niebezpieczny stan, near miss i pierwsza pomoc korzystaja z tej samej obowiazkowej logiki przeplywu zgloszen w systemie.",
    type: "Typ",
    typeUnsafeAct: "Niebezpieczne zachowanie",
    typeUnsafeCondition: "Niebezpieczny stan",
    typeNearMiss: "Near miss",
    typeFirstAid: "Pierwsza pomoc",
    dateTime: "Data i godzina",
    reporterName: "Imie i nazwisko zglaszajacego",
    reporterNameNoNumbers: "Imie i nazwisko zglaszajacego nie moze zawierac cyfr",
    reporterNumber: "Numer zglaszajacego",
    department: "Dzial",
    selectDepartment: "Wybierz dzial",
    location: "Lokalizacja",
    selectLocation: "Wybierz lokalizacje",
    professionalRisk: "Ryzyko zawodowe",
    selectProfessionalRisk: "Wybierz ryzyko zawodowe",
    nearMissType: "Typ near miss",
    selectNearMissType: "Wybierz typ near miss",
    unsafeActType: "Typ niebezpiecznego zachowania",
    selectUnsafeActType: "Wybierz typ niebezpiecznego zachowania",
    shift: "Zmiana",
    selectShift: "Wybierz zmiane",
    involvedWorker: "Zaangazowany pracownik",
    selectInvolvedWorker: "Wybierz pracownika",
    natureOfInjury: "Rodzaj urazu",
    selectNature: "Wybierz rodzaj urazu",
    bodyPartAffected: "Dotknieta czesc ciala",
    selectBodyPart: "Wybierz czesc ciala",
    description: "Opis",
    suggestedAction: "Sugerowane dzialanie",
    submit: "Wyslij zgloszenie",
    submitSuccess: "Zgloszenie zostalo wyslane pomyslnie.",
    submitFailed: "Nie udalo sie wyslac",
  },
  de: {
    title: "Sicherheitsmeldung des Werks",
    intro: "Unsichere Handlung, unsicherer Zustand, Beinaheunfall und Erste Hilfe folgen derselben verpflichtenden Logik wie der Kommunikationsfluss der Software.",
    type: "Typ",
    typeUnsafeAct: "Unsichere Handlung",
    typeUnsafeCondition: "Unsicherer Zustand",
    typeNearMiss: "Beinaheunfall",
    typeFirstAid: "Erste Hilfe",
    dateTime: "Datum und Uhrzeit",
    reporterName: "Name des Meldenden",
    reporterNameNoNumbers: "Der Name des Meldenden darf keine Zahlen enthalten",
    reporterNumber: "Nummer des Meldenden",
    department: "Abteilung",
    selectDepartment: "Abteilung auswahlen",
    location: "Ort",
    selectLocation: "Ort auswahlen",
    professionalRisk: "Berufsrisiko",
    selectProfessionalRisk: "Berufsrisiko auswahlen",
    nearMissType: "Near miss type",
    selectNearMissType: "Near miss type auswahlen",
    unsafeActType: "Art der unsicheren Handlung",
    selectUnsafeActType: "Art der unsicheren Handlung auswahlen",
    shift: "Schicht",
    selectShift: "Schicht auswahlen",
    involvedWorker: "Beteiligter Mitarbeiter",
    selectInvolvedWorker: "Mitarbeiter auswahlen",
    natureOfInjury: "Art der Verletzung",
    selectNature: "Verletzungsart auswahlen",
    bodyPartAffected: "Betroffener Korperteil",
    selectBodyPart: "Korperteil auswahlen",
    description: "Beschreibung",
    suggestedAction: "Vorgeschlagene Massnahme",
    submit: "Meldung senden",
    submitSuccess: "Meldung erfolgreich gesendet.",
    submitFailed: "Senden fehlgeschlagen",
  },
  ro: {
    title: "Raport de Siguranta al Fabricii",
    intro: "Actul nesigur, conditia nesigura, near miss si primul ajutor urmeaza aceeasi logica obligatorie ca fluxul de comunicare din software.",
    type: "Tip",
    typeUnsafeAct: "Act nesigur",
    typeUnsafeCondition: "Conditie nesigura",
    typeNearMiss: "Near miss",
    typeFirstAid: "Prim ajutor",
    dateTime: "Data si ora",
    reporterName: "Numele raportorului",
    reporterNameNoNumbers: "Numele raportorului nu poate contine cifre",
    reporterNumber: "Numarul raportorului",
    department: "Departament",
    selectDepartment: "Selectati departamentul",
    location: "Locatie",
    selectLocation: "Selectati locatia",
    professionalRisk: "Risc profesional",
    selectProfessionalRisk: "Selectati riscul profesional",
    nearMissType: "Tip near miss",
    selectNearMissType: "Selectati tipul near miss",
    unsafeActType: "Tip act nesigur",
    selectUnsafeActType: "Selectati tipul de act nesigur",
    shift: "Schimb",
    selectShift: "Selectati schimbul",
    involvedWorker: "Lucrator implicat",
    selectInvolvedWorker: "Selectati lucratorul implicat",
    natureOfInjury: "Natura leziunii",
    selectNature: "Selectati natura leziunii",
    bodyPartAffected: "Partea corpului afectata",
    selectBodyPart: "Selectati partea corpului",
    description: "Descriere",
    suggestedAction: "Actiune sugerata",
    submit: "Trimite comunicarea",
    submitSuccess: "Comunicarea a fost trimisa cu succes.",
    submitFailed: "Trimiterea a esuat",
  },
  fr: {
    title: "Rapport de Securite de l'Usine",
    intro: "Acte dangereux, condition dangereuse, presque accident et premiers secours suivent la meme logique obligatoire que le flux de communication du logiciel.",
    type: "Type",
    typeUnsafeAct: "Acte dangereux",
    typeUnsafeCondition: "Condition dangereuse",
    typeNearMiss: "Presque accident",
    typeFirstAid: "Premiers secours",
    dateTime: "Date et heure",
    reporterName: "Nom du declarant",
    reporterNameNoNumbers: "Le nom du declarant ne peut pas contenir de chiffres",
    reporterNumber: "Numero du declarant",
    department: "Departement",
    selectDepartment: "Selectionner le departement",
    location: "Lieu",
    selectLocation: "Selectionner le lieu",
    professionalRisk: "Risque professionnel",
    selectProfessionalRisk: "Selectionner le risque professionnel",
    nearMissType: "Type de near miss",
    selectNearMissType: "Selectionner le type de near miss",
    unsafeActType: "Type d'acte dangereux",
    selectUnsafeActType: "Selectionner le type d'acte dangereux",
    shift: "Equipe",
    selectShift: "Selectionner l'equipe",
    involvedWorker: "Travailleur implique",
    selectInvolvedWorker: "Selectionner le travailleur implique",
    natureOfInjury: "Nature de la blessure",
    selectNature: "Selectionner la nature de la blessure",
    bodyPartAffected: "Partie du corps affectee",
    selectBodyPart: "Selectionner la partie du corps",
    description: "Description",
    suggestedAction: "Action suggeree",
    submit: "Envoyer la communication",
    submitSuccess: "Communication envoyee avec succes.",
    submitFailed: "Echec de l'envoi",
  },
};

const BODY_PART_TRANSLATIONS: Record<Exclude<SupportedReportLocale, "en">, Record<string, string>> = {
  pt: {
    BP01: "Cabeça",
    BP02: "Olho esquerdo",
    BP03: "Olho direito",
    BP04: "Ombro esquerdo",
    BP05: "Ombro direito",
    BP06: "Braço esquerdo",
    BP07: "Braço direito",
    BP08: "Mão esquerda",
    BP09: "Mão direita",
    BP10: "Tórax",
    BP11: "Costas superiores",
    BP12: "Costas inferiores",
    BP13: "Abdómen",
    BP14: "Anca esquerda",
    BP15: "Anca direita",
    BP16: "Perna esquerda",
    BP17: "Perna direita",
    BP18: "Joelho esquerdo",
    BP19: "Joelho direito",
    BP20: "Pé esquerdo",
    BP21: "Pé direito",
  },
  it: {
    BP01: "Testa",
    BP02: "Occhio sinistro",
    BP03: "Occhio destro",
    BP04: "Spalla sinistra",
    BP05: "Spalla destra",
    BP06: "Braccio sinistro",
    BP07: "Braccio destro",
    BP08: "Mano sinistra",
    BP09: "Mano destra",
    BP10: "Torace",
    BP11: "Schiena alta",
    BP12: "Schiena bassa",
    BP13: "Addome",
    BP14: "Anca sinistra",
    BP15: "Anca destra",
    BP16: "Gamba sinistra",
    BP17: "Gamba destra",
    BP18: "Ginocchio sinistro",
    BP19: "Ginocchio destro",
    BP20: "Piede sinistro",
    BP21: "Piede destro",
  },
  pl: {
    BP01: "Glowa",
    BP02: "Lewe oko",
    BP03: "Prawe oko",
    BP04: "Lewe ramie",
    BP05: "Prawe ramie",
    BP06: "Lewe przedramie",
    BP07: "Prawe przedramie",
    BP08: "Lewa dlon",
    BP09: "Prawa dlon",
    BP10: "Klatka piersiowa",
    BP11: "Gorna czesc plecow",
    BP12: "Dolna czesc plecow",
    BP13: "Brzuch",
    BP14: "Lewe biodro",
    BP15: "Prawe biodro",
    BP16: "Lewa noga",
    BP17: "Prawa noga",
    BP18: "Lewe kolano",
    BP19: "Prawe kolano",
    BP20: "Lewa stopa",
    BP21: "Prawa stopa",
  },
  de: {
    BP01: "Kopf",
    BP02: "Linkes Auge",
    BP03: "Rechtes Auge",
    BP04: "Linke Schulter",
    BP05: "Rechte Schulter",
    BP06: "Linker Arm",
    BP07: "Rechter Arm",
    BP08: "Linke Hand",
    BP09: "Rechte Hand",
    BP10: "Brustkorb",
    BP11: "Oberer Rucken",
    BP12: "Unterer Rucken",
    BP13: "Bauch",
    BP14: "Linke Hufte",
    BP15: "Rechte Hufte",
    BP16: "Linkes Bein",
    BP17: "Rechtes Bein",
    BP18: "Linkes Knie",
    BP19: "Rechtes Knie",
    BP20: "Linker Fuss",
    BP21: "Rechter Fuss",
  },
  ro: {
    BP01: "Cap",
    BP02: "Ochiul stang",
    BP03: "Ochiul drept",
    BP04: "Umarul stang",
    BP05: "Umarul drept",
    BP06: "Bratul stang",
    BP07: "Bratul drept",
    BP08: "Mana stanga",
    BP09: "Mana dreapta",
    BP10: "Torace",
    BP11: "Partea superioara a spatelui",
    BP12: "Partea inferioara a spatelui",
    BP13: "Abdomen",
    BP14: "Soldul stang",
    BP15: "Soldul drept",
    BP16: "Piciorul stang",
    BP17: "Piciorul drept",
    BP18: "Genunchiul stang",
    BP19: "Genunchiul drept",
    BP20: "Laba piciorului stang",
    BP21: "Laba piciorului drept",
  },
  fr: {
    BP01: "Tete",
    BP02: "Oeil gauche",
    BP03: "Oeil droit",
    BP04: "Epaule gauche",
    BP05: "Epaule droite",
    BP06: "Bras gauche",
    BP07: "Bras droit",
    BP08: "Main gauche",
    BP09: "Main droite",
    BP10: "Thorax",
    BP11: "Haut du dos",
    BP12: "Bas du dos",
    BP13: "Abdomen",
    BP14: "Hanche gauche",
    BP15: "Hanche droite",
    BP16: "Jambe gauche",
    BP17: "Jambe droite",
    BP18: "Genou gauche",
    BP19: "Genou droit",
    BP20: "Pied gauche",
    BP21: "Pied droit",
  },
};

const INJURY_TYPE_TRANSLATIONS: Record<Exclude<SupportedReportLocale, "en">, readonly string[]> = {
  pt: [
    "Contusão (pisadura)",
    "Corte / laceração",
    "Perfuração",
    "Amputação (total ou parcial)",
    "Esmagamento",
    "Hematoma",
    "Abrasão / escoriação",
    "Fratura simples",
    "Fratura exposta",
    "Fratura múltipla",
    "Fissura óssea",
    "Luxação",
    "Subluxação",
    "Distensão muscular",
    "Rotura muscular",
    "Entorse",
    "Rotura de ligamentos",
    "Tendinite",
    "Tenossinovite",
    "Mialgia (dor muscular)",
    "Entorse articular",
    "Inflamação articular",
    "Limitação de movimentos",
    "Derrame articular",
    "Concussão cerebral",
    "Traumatismo cranioencefálico (TCE)",
    "Lesão nervosa periférica",
    "Dormência / parestesia",
    "Perda de consciência",
    "Vertigens pós-trauma",
    "Queimadura térmica",
    "Queimadura química",
    "Queimadura elétrica",
    "Dermatite de contacto",
    "Irritação cutânea",
    "Bolhas",
    "Corpo estranho no olho",
    "Irritação ocular",
    "Queimadura ocular",
    "Perda parcial ou total da visão",
    "Trauma acústico",
    "Perda auditiva temporária",
    "Perda auditiva permanente",
    "Dor no ouvido",
    "Lesão por esforços repetitivos (LER)",
    "Distúrbios músculo-esqueléticos relacionados com o trabalho (DORT)",
    "Síndrome do túnel cárpico",
    "Lombalgia",
    "Cervicalgia",
    "Hemorragia interna",
    "Lesão em órgãos internos",
    "Contusão torácica",
    "Traumatismo abdominal",
    "Intoxicação",
    "Asfixia",
    "Choque elétrico",
    "Golpe de calor",
    "Hipotermia",
    "Reação alérgica",
  ],
  it: [
    "Contusione",
    "Taglio / lacerazione",
    "Perforazione",
    "Amputazione (totale o parziale)",
    "Schiacciamento",
    "Ematoma",
    "Abrasione / escoriazione",
    "Frattura semplice",
    "Frattura esposta",
    "Frattura multipla",
    "Fessura ossea",
    "Lussazione",
    "Sublussazione",
    "Stiramento muscolare",
    "Rottura muscolare",
    "Distorsione",
    "Rottura dei legamenti",
    "Tendinite",
    "Tenosinovite",
    "Mialgia (dolore muscolare)",
    "Distorsione articolare",
    "Infiammazione articolare",
    "Limitazione dei movimenti",
    "Versamento articolare",
    "Commozione cerebrale",
    "Trauma cranioencefalico (TCE)",
    "Lesione nervosa periferica",
    "Intorpidimento / parestesia",
    "Perdita di coscienza",
    "Vertigini post-trauma",
    "Ustione termica",
    "Ustione chimica",
    "Ustione elettrica",
    "Dermatite da contatto",
    "Irritazione cutanea",
    "Vesciche",
    "Corpo estraneo nell'occhio",
    "Irritazione oculare",
    "Ustione oculare",
    "Perdita parziale o totale della vista",
    "Trauma acustico",
    "Perdita uditiva temporanea",
    "Perdita uditiva permanente",
    "Dolore all'orecchio",
    "Lesione da sforzi ripetitivi (RSI)",
    "Disturbi muscoloscheletrici correlati al lavoro (DMS)",
    "Sindrome del tunnel carpale",
    "Lombalgia",
    "Cervicalgia",
    "Emorragia interna",
    "Lesione agli organi interni",
    "Contusione toracica",
    "Trauma addominale",
    "Intossicazione",
    "Asfissia",
    "Scossa elettrica",
    "Colpo di calore",
    "Ipotermia",
    "Reazione allergica",
  ],
  pl: [
    "Stluczenie",
    "Ciecie / rozerwanie",
    "Przebicie",
    "Amputacja (calkowita lub czesciowa)",
    "Zmiazdenie",
    "Krwiak",
    "Otarcie / zadrapanie",
    "Zlamanie proste",
    "Zlamanie otwarte",
    "Zlamanie mnogie",
    "Pekniecie kosci",
    "Zwichniecie",
    "Podwichniecie",
    "Naciagniecie miesnia",
    "Zerwanie miesnia",
    "Skrecenie",
    "Zerwanie wiezadel",
    "Zapalenie sciegna",
    "Zapalenie pochewki sciegnistej",
    "Mialgia (bol miesni)",
    "Skrecenie stawu",
    "Zapalenie stawu",
    "Ograniczenie ruchow",
    "Wysiek stawowy",
    "Wstrzas mozgu",
    "Uraz czaszkowo-mozgowy (TBI)",
    "Uszkodzenie nerwu obwodowego",
    "Dretwienie / parestezja",
    "Utrata przytomnosci",
    "Zawroty glowy po urazie",
    "Oparzenie termiczne",
    "Oparzenie chemiczne",
    "Oparzenie elektryczne",
    "Kontaktowe zapalenie skory",
    "Podraznienie skory",
    "Pecherze",
    "Cialo obce w oku",
    "Podraznienie oka",
    "Oparzenie oka",
    "Czesciowa lub calkowita utrata wzroku",
    "Uraz akustyczny",
    "Tymczasowa utrata sluchu",
    "Trwala utrata sluchu",
    "Bol ucha",
    "Uraz od powtarzalnych czynnosci (RSI)",
    "Miesniowo-szkieletowe schorzenia zwiazane z praca (MSD)",
    "Zespol ciesni nadgarstka",
    "Bol dolnej czesci plecow",
    "Bol szyi",
    "Krwotok wewnetrzny",
    "Uszkodzenie narzadow wewnetrznych",
    "Stluczenie klatki piersiowej",
    "Uraz brzucha",
    "Zatrucie",
    "Uduszenie",
    "Porazenie pradem",
    "Udar cieplny",
    "Hipotermia",
    "Reakcja alergiczna",
  ],
  de: [
    "Prellung",
    "Schnitt / Platzwunde",
    "Durchstich",
    "Amputation (vollstandig oder teilweise)",
    "Quetschung",
    "Hamatom",
    "Abschurfung / Schurfwunde",
    "Einfache Fraktur",
    "Offene Fraktur",
    "Mehrfachfraktur",
    "Knochenriss",
    "Luxation",
    "Subluxation",
    "Muskelzerrung",
    "Muskelriss",
    "Verstauchung",
    "Banderiss",
    "Sehnenentzundung",
    "Sehnenscheidenentzundung",
    "Myalgie (Muskelschmerz)",
    "Gelenkverstauchung",
    "Gelenkentzundung",
    "Bewegungseinschrankung",
    "Gelenkerguss",
    "Gehirnerschutterung",
    "Schadel-Hirn-Trauma (SHT)",
    "Periphere Nervenverletzung",
    "Taubheit / Parasthetie",
    "Bewusstseinsverlust",
    "Schwindel nach Trauma",
    "Thermische Verbrennung",
    "Chemische Verbrennung",
    "Elektrische Verbrennung",
    "Kontaktdermatitis",
    "Hautreizung",
    "Blasen",
    "Fremdkorper im Auge",
    "Augenreizung",
    "Augenverbrennung",
    "Teilweiser oder vollstandiger Sehverlust",
    "Akustisches Trauma",
    "Vorubergehender Horverlust",
    "Dauerhafter Horverlust",
    "Ohrenschmerzen",
    "Verletzung durch repetitive Belastung (RSI)",
    "Arbeitsbedingte Muskel-Skelett-Erkrankung (MSE)",
    "Karpaltunnelsyndrom",
    "Lumbalgie",
    "Zervikalgie",
    "Innere Blutung",
    "Verletzung innerer Organe",
    "Thoraxprellung",
    "Bauchtrauma",
    "Vergiftung",
    "Erstickung",
    "Elektrischer Schlag",
    "Hitzschlag",
    "Unterkuhlung",
    "Allergische Reaktion",
  ],
  ro: [
    "Contuzie",
    "Taietura / laceratie",
    "Perforatie",
    "Amputatie (totala sau partiala)",
    "Strivire",
    "Hematom",
    "Abraziune / escoriatie",
    "Fractura simpla",
    "Fractura deschisa",
    "Fractura multipla",
    "Fisura osoasa",
    "Luxatie",
    "Subluxatie",
    "Intindere musculara",
    "Ruptura musculara",
    "Entorsa",
    "Ruptura de ligamente",
    "Tendinita",
    "Tenosinovita",
    "Mialgie (durere musculara)",
    "Entorsa articulara",
    "Inflamatie articulara",
    "Limitarea miscarilor",
    "Revarsat articular",
    "Comotie cerebrala",
    "Traumatism cranio-cerebral (TCC)",
    "Leziune nervoasa periferica",
    "Amorteala / parestezie",
    "Pierdere a cunostintei",
    "Ameteli post-trauma",
    "Arsura termica",
    "Arsura chimica",
    "Arsura electrica",
    "Dermatita de contact",
    "Iritatie cutanata",
    "Basici",
    "Corp strain in ochi",
    "Iritatie oculara",
    "Arsura oculara",
    "Pierderea partiala sau totala a vederii",
    "Trauma acustica",
    "Pierderea temporara a auzului",
    "Pierderea permanenta a auzului",
    "Durere de ureche",
    "Leziune prin efort repetitiv (RSI)",
    "Tulburari musculo-scheletice legate de munca (MSD)",
    "Sindrom de tunel carpian",
    "Lombalgie",
    "Cervicalgie",
    "Hemoragie interna",
    "Leziune a organelor interne",
    "Contuzie toracica",
    "Traumatism abdominal",
    "Intoxicatie",
    "Asfixie",
    "Soc electric",
    "Insolatie",
    "Hipotermie",
    "Reactie alergica",
  ],
  fr: [
    "Contusion",
    "Coupure / laceration",
    "Perforation",
    "Amputation (totale ou partielle)",
    "Ecrasement",
    "Hematome",
    "Abrasion / ecorchure",
    "Fracture simple",
    "Fracture ouverte",
    "Fracture multiple",
    "Fissure osseuse",
    "Luxation",
    "Subluxation",
    "Elongation musculaire",
    "Dechirure musculaire",
    "Entorse",
    "Rupture des ligaments",
    "Tendinite",
    "Tenosynovite",
    "Myalgie (douleur musculaire)",
    "Entorse articulaire",
    "Inflammation articulaire",
    "Limitation des mouvements",
    "Epanchement articulaire",
    "Commotion cerebrale",
    "Traumatisme cranio-encephalique (TCE)",
    "Lision nerveuse peripherique",
    "Engourdissement / paresthesie",
    "Perte de connaissance",
    "Vertiges post-traumatiques",
    "Brulure thermique",
    "Brulure chimique",
    "Brulure electrique",
    "Dermatite de contact",
    "Irritation cutanee",
    "Cloques",
    "Corps etranger dans l'oeil",
    "Irritation oculaire",
    "Brulure oculaire",
    "Perte partielle ou totale de la vision",
    "Traumatisme acoustique",
    "Perte auditive temporaire",
    "Perte auditive permanente",
    "Douleur a l'oreille",
    "Lesion due aux efforts repetitifs (RSI)",
    "Troubles musculo-squelettiques lies au travail (TMS)",
    "Syndrome du canal carpien",
    "Lombalgie",
    "Cervicalgie",
    "Hemorragie interne",
    "Lesion des organes internes",
    "Contusion thoracique",
    "Traumatisme abdominal",
    "Intoxication",
    "Asphyxie",
    "Choc electrique",
    "Coup de chaleur",
    "Hypothermie",
    "Reaction allergique",
  ],
};

type CatalogRow = {
  code?: string | null;
  name: string;
};

export type LocalizedCatalogRow = CatalogRow & {
  id: string;
};

function normalizeLocale(language: string | null | undefined): SupportedReportLocale {
  if (language && language in REPORT_TEXTS) {
    return language as SupportedReportLocale;
  }
  return "en";
}

function normalizeCatalogText(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function injuryTypeIndexFromCode(code?: string | null) {
  if (!code) return null;
  const standardMatch = code.match(/^IT(\d{2})$/i);
  if (standardMatch) return Number(standardMatch[1]) - 1;

  const plantMatch = code.match(/-IT-(\d{3})$/i);
  if (plantMatch) return Number(plantMatch[1]) - 1;

  return null;
}

export function getPublicReportText(language: string | null | undefined) {
  const locale = normalizeLocale(language);
  return {
    locale,
    text: REPORT_TEXTS[locale],
  };
}

export function getLocalizedShiftName(row: CatalogRow, language: string | null | undefined) {
  const locale = normalizeLocale(language);
  if (locale !== "pt") return row.name;

  const normalizedName = normalizeCatalogText(row.name);
  const normalizedCode = row.code?.trim().toUpperCase();

  if (
    normalizedName === "central" ||
    normalizedName === "shift central" ||
    normalizedCode === "S4" ||
    normalizedCode === "SC" ||
    normalizedCode === "CENTRAL"
  ) {
    return "Central";
  }

  const codeMatch = row.code?.match(/^S(\d+)$/i);
  if (codeMatch) {
    return `Turno ${codeMatch[1]}`;
  }

  const nameMatch = row.name.match(/^Shift\s+(.+)$/i);
  if (nameMatch) {
    return `Turno ${nameMatch[1]}`;
  }

  return row.name;
}

export function getLocalizedBodyPartName(row: CatalogRow, language: string | null | undefined) {
  const locale = normalizeLocale(language);
  if (locale !== "en" && row.code) {
    const translated = BODY_PART_TRANSLATIONS[locale]?.[row.code];
    if (translated) {
      return translated;
    }
  }
  return row.name;
}

export function getLocalizedInjuryTypeName(row: CatalogRow, language: string | null | undefined) {
  const locale = normalizeLocale(language);
  if (locale !== "en") {
    const index = injuryTypeIndexFromCode(row.code);
    if (index !== null && INJURY_TYPE_TRANSLATIONS[locale]?.[index]) {
      return INJURY_TYPE_TRANSLATIONS[locale][index];
    }
  }
  return row.name;
}

export function dedupeCatalogRows<T extends CatalogRow>(rows: T[], getLabel: (row: T) => string) {
  const seen = new Set<string>();
  return rows.filter((row) => {
    const key = normalizeCatalogText(getLabel(row));
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function localizeBodyPartRows<T extends LocalizedCatalogRow>(rows: T[], language: string | null | undefined) {
  return rows
    .map((row) => ({
      ...row,
      name: getLocalizedBodyPartName(row, language),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function localizeInjuryTypeRows<T extends LocalizedCatalogRow>(rows: T[], language: string | null | undefined) {
  return rows
    .map((row) => ({
      ...row,
      name: getLocalizedInjuryTypeName(row, language),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
