import type { ActionCategory, ActionPriority, SEWOStatus } from "@prisma/client";
import type { AppLocale } from "@/lib/i18n/routing";

export type RootCauseGroup = {
  heading: string;
  columns: Array<{
    title: string;
    items: string[];
  }>;
};

export const BASE_ROOT_CAUSE_GROUPS: RootCauseGroup[] = [
  {
    heading: "Unsafe Action",
    columns: [
      { title: "1 Competence / Knowledge", items: ["1.1 Inadequate training", "1.2 Limited experience with the specific task"] },
      { title: "2 Attitude / Behavior", items: ["2.1 Lack of concentration", "2.2 Incorrect use of protective items", "2.3 Breaking rules for safety", "2.4 Failure to respect work cycles and procedure", "2.5 Doubtful circumstances", "2.6 Failure to use PPE"] },
      { title: "3 Management", items: ["3.1 PPE inadequate", "3.2 Unfitness for the job", "3.3 Maintenance cycles not performed", "3.4 Cleaning cycles not performed", "3.5 Pressure", "3.6 Other"] },
      { title: "4 Precaution / Attention", items: ["4.1 Excess self-confidence", "4.2 Execution of operations outside of his/her competence", "4.3 Lack of communication"] },
    ],
  },
  {
    heading: "Unsafe Condition",
    columns: [
      { title: "5 Personal Condition", items: ["5.1 Physical problems / Physical fatigue", "5.2 Sudden illness", "5.3 Personal / family problems", "5.4 Health problems"] },
      { title: "6 Facilities / Equipment", items: ["6.1 Equipment facilities inadequate", "6.2 Lack of maintenance", "6.3 Weakness in design", "6.4 Anomalous functioning of equipment / facilities", "6.5 Failure / breakage", "6.6 Poor lighting", "6.7 Lack of cleaning cycles", "6.8 Erroneous manufacturing / installation"] },
      { title: "7 Procedure / Systems", items: ["7.1 Lack of standard procedure and/or safety rules", "7.2 Procedure inadequate", "7.3 Protective items not suitable", "7.4 Complex work methods", "7.5 Others"] },
    ],
  },
];

export const BASE_SEWO_UI = {
  pageTitle: "S-EWO",
  reportTitle: "S-EWO Investigation Report",
  summaryReportTitle: "S-EWO Summary Report",
  summaryReportReference: "S-EWO Reference",
  summaryReportGeneralInfo: "1. General Information",
  summaryReportOccurrenceDate: "Occurrence Date",
  summaryReportOccurrenceType: "Occurrence Type",
  summaryReportLocation: "Location / Workstation",
  summaryReportInjuryNature: "Nature of Injury",
  summaryReportDescriptionSection: "2. Occurrence Description",
  summaryReportAnalysisSection: "3. Analysis",
  summaryReportRootCause: "Selected Root Cause",
  summaryReportClassification: "SIF / PSIF Classification",
  summaryReportActionPlanSection: "4. Action Plan",
  summaryReportPhotoEvidenceSection: "5. Photo Evidence",
  summaryReportNotApplicable: "Not applicable",
  generatedOn: "Generated on",
  plant: "Plant",
  createButton: "Create S-EWO",
  hideCreationButton: "Hide creation",
  tableDate: "Date",
  tableLocation: "Location",
  tableType: "S-EWO Type",
  tableStatus: "Status",
  tableEdit: "Edit",
  editButton: "Edit",
  noRecords: "No S-EWO records found.",
  selectedTitle: "S-EWO selected",
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  close: "Close",
  summaryTitle: "Summary",
  summaryStatus: "Status",
  summaryPerformedBy: "Performed by",
  summaryCommunication: "Communication",
  exportSummaryReport: "Export summary report",
  exportCompleteReport: "Export complete report",
  openSewoTitle: "Open S-EWO",
  noOpenSewo: "No open S-EWO records.",
  investigationTitle: "S-EWO Investigation",
  associatedCommunication: "Associated communication",
  continueWithoutLinkedCommunication: "Continue without associated communication",
  manualMode: "Manual mode",
  skipLink: "Skip link",
  month: "Month",
  communication: "Communication",
  linked: "Linked",
  selected: "Selected",
  choose: "Choose",
  noCommunicationsForMonth: "No communications available for this month.",
  noCauseCatalog: "No cause catalog available.",
  selectCommunicationOrContinue: "Select a communication or continue without one.",
  createSuccess: "S-EWO created.",
  createError: "Failed to create S-EWO",
  editSewoTitle: "Edit S-EWO investigation",
  updateSewo: "Save S-EWO",
  saveChanges: "Save changes",
  resubmitSewo: "Resubmit S-EWO",
  resubmitSuccess: "S-EWO resubmitted for N1 approval.",
  updateSuccess: "S-EWO updated.",
  updateError: "Failed to update S-EWO",
  saveDraft: "Save draft",
  draftSaved: "S-EWO draft saved.",
  draftSaveError: "Failed to save S-EWO draft",
  notSpecified: "Not specified",
  preparePhotoUploadError: "Failed to prepare photo upload",
  uploadPhotoError: "Failed to upload {name}",
  eventClassification: "Event classification",
  selectedCommunication: "Selected communication",
  manualWithoutCommunication: "Manual S-EWO without associated communication.",
  openActionsFromCommunication: "Open actions from communication",
  linkedActions: "Linked actions",
  openAction: "Open action",
  saveAction: "Save action",
  savingAction: "Saving...",
  updateActionSuccess: "Communication actions updated.",
  updateActionError: "Failed to update action",
  createLinkedAction: "Create linked action",
  linkedActionCreated: "Linked action created.",
  linkedActionCreateError: "Failed to create linked action",
  statusManagement: "Status management",
  statusChangeReason: "Reason for the status change",
  closeSewo: "Set status to Closed",
  statusChangeSaved: "S-EWO status updated successfully.",
  statusChangeFailed: "Failed to update S-EWO status.",
  statusReasonRequired: "Write at least 5 characters to justify the status change.",
  cannotCloseWithOpenActions: "Não é possível fechar este S-EWO porque existem ações associadas ainda em aberto.",
  validationFeedbackTitle: "N1 validation feedback",
  rejectionFeedbackTitle: "N1 rejection feedback",
  validatedBy: "Validated by",
  rejectedBy: "Rejected by",
  reviewedAt: "Reviewed at",
  expandSection: "Show",
  collapseSection: "Hide",
  area: "Area",
  selectArea: "Select area",
  workstation: "Workstation",
  selectWorkstation: "Select workstation",
  shift: "Shift",
  selectShift: "Select shift",
  involvedPerson: "Involved person",
  selectWorker: "Select worker",
  nature: "Nature",
  selectNature: "Select nature of injury",
  departmentNotDefined: "Department not defined",
  usualJob: "Usual job",
  yes: "Yes",
  no: "No",
  whichOperation: "Which operation",
  whichOperationPlaceholder: "Type of operation",
  anatomicalModel: "Anatomical model",
  evidenceUpload: "Evidence / Photo Upload",
  evidenceUploadDescription: "Add photos or files before starting the analysis section.",
  filesReadySuffix: "file(s) ready for upload.",
  caption: "Caption",
  captionPlaceholder: "Optional caption",
  noEvidenceFiles: "No evidence images selected.",
  howDidTheAccidentHappen: "How did the accident happen?",
  immediateCorrectiveActionPlan: "Immediate corrective action plan",
  analysis: "Analysis",
  analysisText: "Analysis text",
  fiveWhy: "5 Why",
  noFiveWhyAnalysis: "No 5 Why analysis registered.",
  question: "Question",
  addWhy: "Add Why",
  whyLabel: "Why",
  answerLabel: "Answer",
  sifPsifDecisionTree: "SIF / PSIF Decision Tree",
  sifPsifInformationTitle: "SIF / PSIF classification",
  sifPsifInformationBody: "The tree classifies the event according to the actual consequence and the potential severity. A fatality or serious injury corresponds to a SIF. When there is no serious consequence, but the event involved an exposure realistically capable of causing a serious injury or fatality, it may be classified as PSIF. Answer based on the actual conditions of the event and the existing controls.",
  sifPsifInformationButtonLabel: "Information about SIF/PSIF classification",
  eventReported: "Event reported",
  actualSifQuestion: "Was it an actual SIF event? Did a fatality or life altering/threatening injury/illness occur?",
  sifPsifExposureQuestions: {
    suspendedLoad: "Did the event involve pinched between or in the danger zone of a suspended load? (lifting operations)",
    mobileEquipment: "Did the event involve contact with mobile equipment? (transport safety)",
    energyIsolation: "Did the event involve energy isolation / Lock out Tag Out",
    workAtHeight: "Did the event involve falling from a height >2m? (Work at Height)",
    movingEquipment: "Did the event involve contact with moving equipment (Machinery Safety)",
    confinedSpace: "Did the event involve Confined Space Entry?",
    significantMassEnergy: "Did the event involve pinched between, caught in or struck by sharp edge, release of significant mass or energy?",
  },
  sifPsifReasonabilityCheck: "PSIF Reasonability Check",
  repeatedSifPotentialQuestion: "Would a SIF occur if the incident were repeated 100 times?",
  oneWhatIfAwayQuestion: "Is this situation one 'What If' away from a significant incident?",
  noPsifExplanation: "Written explanation why PSIF definition does not apply",
  noPsifExplanationPlaceholder: "Explain why the event does not meet the PSIF definition.",
  sifPsifResult: "SIF / PSIF result",
  sifResult: "SIF",
  psifResult: "PSIF",
  noPsifResult: "No PSIF",
  pendingResult: "Pending",
  n1ValidationTitle: "S-EWO pending N1 approval",
  n1ValidationSubtitle: "Submitted S-EWO records from N2 and N3 awaiting N1 decision.",
  n1ValidationEmpty: "No S-EWO records pending N1 approval.",
  n1ValidationCommunicationSection: "Communication validation queue",
  n1ValidationSewoSection: "S-EWO approval queue",
  n1ValidationSubmittedBy: "Submitted by",
  n1ValidationSubmittedAt: "Submitted at",
  n1ValidationPlant: "Plant",
  n1ValidationOccurrence: "Occurrence type",
  n1ValidationStatus: "Status",
  n1ValidationLocation: "Location",
  n1ValidationAnalysisDate: "Analysis date",
  n1ValidationSifPsif: "SIF / PSIF",
  n1ValidationPriority: "Priority SIF/PSIF",
  n1ValidationComment: "Decision comment",
  n1ValidationCommentPlaceholder: "Add the validation or rejection reason.",
  n1ValidationApprove: "Validate S-EWO",
  n1ValidationReject: "Reject S-EWO",
  n1ValidationOpenSewo: "Open S-EWO",
  n1ValidationExportPdf: "PDF",
  n1ValidationExportExcel: "Excel",
  n1ValidationConfirmReject: "Reject this S-EWO?",
  n1ValidationSaved: "Decision saved.",
  n1ValidationFailed: "Failed to save decision.",
  n1ValidationSaving: "Saving...",
  rootCauseAnalysis: "Root Cause Analysis",
  rootCauses: "Root Causes",
  rootCause: "Root cause",
  noRootCauseDetails: "No root cause details registered.",
  previousDetected: "Have previous UA / UC been detected?",
  previousDetectedDescription: "Describe previous detection",
  actionPlan: "Action Plan",
  noLinkedActions: "No linked actions.",
  addAction: "Add action",
  action: "Action",
  remove: "Remove",
  title: "Title",
  category: "Category",
  description: "Description",
  owner: "Owner",
  selectOwner: "Select owner",
  priority: "Priority",
  dueDate: "Due date",
  field: "Field",
  value: "Value",
  cause: "Cause",
  comment: "Comment",
  noRecordsShort: "No records",
  createSewo: "Create S-EWO",
  actionStatusLabels: {
    OPEN: "Open",
    ONGOING: "Ongoing",
    CLOSED: "Closed",
  } as Record<string, string>,
  sewoStatusLabels: {
    DRAFT: "Draft",
    IN_APPROVAL: "Submitted",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    CLOSED: "Closed",
  } as Record<SEWOStatus | string, string>,
  communicationTypeLabels: {
    UNSAFE_ACT: "Unsafe Act",
    UNSAFE_CONDITION: "Unsafe Condition",
    NEAR_MISS: "Near Miss",
    FIRST_AID: "First Aid",
    ACCIDENT: "Injury",
  } as Record<string, string>,
  priorityLabels: {
    LOW: "Low",
    MEDIUM: "Medium",
    HIGH: "High",
  } as Record<ActionPriority | string, string>,
  categoryLabels: {
    CORRECTIVE: "Corrective",
    PREVENTIVE: "Preventive",
    IMPROVEMENT: "Improvement",
  } as Record<ActionCategory | string, string>,
  bodyZonePicker: {
    selectPlaceholder: "Body part affected",
    helperDefault: "Select from the list or move over the anatomical model and click the affected area.",
    previewMapped: "Previewing {name}. Click to select it on the {views}.",
    previewUnmapped: "Previewing {name}. This body part is not yet mapped on the model.",
    selectedMapped: "Selected: {name}. Highlighted on the {views}.",
    selectedUnmapped: "Selected: {name}. This body part is not yet mapped on the model.",
    frontView: "Front view",
    backView: "Back view",
    moveOverModel: "Move over the model",
    notShownOnView: "Not shown on this view",
    noMappedArea: "No mapped area",
    frontAndBackViews: "front and back views",
    frontViewOnly: "front view",
    backViewOnly: "back view",
    notMapped: "not mapped on the anatomical model",
  },
} as const;

type WidenStrings<T> = {
  [Key in keyof T]: T[Key] extends string
    ? string
    : T[Key] extends Record<string, unknown>
      ? WidenStrings<T[Key]>
      : T[Key];
};

export type SewoUiBase = WidenStrings<typeof BASE_SEWO_UI>;

export type SewoUi = SewoUiBase & {
  locale: string;
};

type SifPsifInformationCopy = Pick<
  SewoUiBase,
  "sifPsifInformationTitle" | "sifPsifInformationBody" | "sifPsifInformationButtonLabel"
>;

const SIF_PSIF_INFORMATION_COPY: Record<AppLocale, SifPsifInformationCopy> = {
  en: {
    sifPsifInformationTitle: "SIF / PSIF classification",
    sifPsifInformationBody: "The tree classifies the event according to the actual consequence and the potential severity. A fatality or serious injury corresponds to a SIF. When there is no serious consequence, but the event involved an exposure realistically capable of causing a serious injury or fatality, it may be classified as PSIF. Answer based on the actual conditions of the event and the existing controls.",
    sifPsifInformationButtonLabel: "Information about SIF/PSIF classification",
  },
  it: {
    sifPsifInformationTitle: "Classificazione SIF / PSIF",
    sifPsifInformationBody: "L’albero classifica l’evento in base alla conseguenza reale e al potenziale di gravità. Un decesso o una lesione grave corrisponde a un SIF. Quando non si è verificata una conseguenza grave, ma l’evento ha comportato un’esposizione realisticamente in grado di causare una lesione grave o un decesso, può essere classificato come PSIF. Rispondere in base alle condizioni reali dell’evento e ai controlli esistenti.",
    sifPsifInformationButtonLabel: "Informazioni sulla classificazione SIF/PSIF",
  },
  pt: {
    sifPsifInformationTitle: "Classificação SIF / PSIF",
    sifPsifInformationBody: "A árvore classifica o evento pela consequência real e pelo potencial de gravidade. Uma fatalidade ou lesão grave corresponde a um SIF. Quando não existe uma consequência grave, mas o evento envolveu uma exposição capaz de causar realisticamente uma lesão grave ou fatalidade, poderá ser classificado como PSIF. Responda com base nas condições reais do evento e nos controlos existentes.",
    sifPsifInformationButtonLabel: "Informação sobre a classificação SIF/PSIF",
  },
  pl: {
    sifPsifInformationTitle: "Klasyfikacja SIF / PSIF",
    sifPsifInformationBody: "Drzewo klasyfikuje zdarzenie na podstawie rzeczywistych skutków i potencjalnej dotkliwości. Wypadek śmiertelny lub poważny uraz odpowiada klasyfikacji SIF. Jeśli nie wystąpiły poważne skutki, ale zdarzenie wiązało się z narażeniem, które realnie mogło spowodować poważny uraz lub śmierć, może zostać sklasyfikowane jako PSIF. Odpowiadaj na podstawie rzeczywistych warunków zdarzenia i istniejących środków kontroli.",
    sifPsifInformationButtonLabel: "Informacje o klasyfikacji SIF/PSIF",
  },
  de: {
    sifPsifInformationTitle: "SIF-/PSIF-Klassifizierung",
    sifPsifInformationBody: "Der Entscheidungsbaum klassifiziert das Ereignis anhand der tatsächlichen Folgen und des Schwerepotenzials. Ein Todesfall oder eine schwere Verletzung entspricht einem SIF. Wenn keine schwerwiegenden Folgen eingetreten sind, das Ereignis jedoch eine Exposition beinhaltete, die realistischerweise eine schwere Verletzung oder einen Todesfall hätte verursachen können, kann es als PSIF eingestuft werden. Beantworten Sie die Fragen auf Grundlage der tatsächlichen Bedingungen des Ereignisses und der vorhandenen Kontrollen.",
    sifPsifInformationButtonLabel: "Informationen zur SIF-/PSIF-Klassifizierung",
  },
  ro: {
    sifPsifInformationTitle: "Clasificare SIF / PSIF",
    sifPsifInformationBody: "Arborele clasifică evenimentul în funcție de consecința reală și de potențialul de gravitate. Un deces sau o vătămare gravă corespunde unui SIF. Atunci când nu există o consecință gravă, dar evenimentul a implicat o expunere capabilă în mod realist să provoace o vătămare gravă sau un deces, acesta poate fi clasificat drept PSIF. Răspundeți pe baza condițiilor reale ale evenimentului și a măsurilor de control existente.",
    sifPsifInformationButtonLabel: "Informații despre clasificarea SIF/PSIF",
  },
  fr: {
    sifPsifInformationTitle: "Classification SIF / PSIF",
    sifPsifInformationBody: "L’arbre classe l’événement selon la conséquence réelle et le potentiel de gravité. Un décès ou une blessure grave correspond à un SIF. Lorsqu’il n’y a pas eu de conséquence grave, mais que l’événement a impliqué une exposition pouvant réellement provoquer une blessure grave ou un décès, il peut être classé comme PSIF. Répondez en vous fondant sur les conditions réelles de l’événement et les mesures de maîtrise existantes.",
    sifPsifInformationButtonLabel: "Informations sur la classification SIF/PSIF",
  },
};

export function getSifPsifInformationCopy(locale: string): SifPsifInformationCopy {
  return SIF_PSIF_INFORMATION_COPY[locale as AppLocale] ?? SIF_PSIF_INFORMATION_COPY.en;
}

export type BodyZonePickerLabels = SewoUi["bodyZonePicker"];

export function formatLocalizedSewoStatus(status: string, ui: Pick<SewoUi, "sewoStatusLabels">) {
  return ui.sewoStatusLabels[status] ?? status;
}

export function formatLocalizedCommunicationType(type: string, ui: Pick<SewoUi, "communicationTypeLabels">) {
  return ui.communicationTypeLabels[type] ?? type;
}
