import type { AppLocale } from "@/lib/i18n/routing";

export const DASHBOARD_LANGUAGES = [
  { code: "en", label: "English", flag: "GB" },
  { code: "it", label: "Italiano", flag: "IT" },
  { code: "pt", label: "Português", flag: "PT" },
  { code: "pl", label: "Polski", flag: "PL" },
  { code: "de", label: "Deutsch", flag: "DE" },
  { code: "ro", label: "Română", flag: "RO" },
  { code: "fr", label: "Français", flag: "FR" },
] as const satisfies Array<{ code: AppLocale; label: string; flag: string }>;

const UI_DICTIONARY = {
  en: {
    modules: {
      safetyDashboard: "Safety Dashboard",
      environmentDashboard: "Environment Dashboard",
      validation: "Validation",
      communications: "Communications",
      actions: "Actions",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Monthly Inputs",
      contractors: "Contractors",
      occupationalHealth: "Occupational Health",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Group KPI's",
      settings: "Settings",
    },
    dashboard: {
      plantTitle: "Safety Dashboard",
      plantDescription: "All indicators react to the selected period and summarize this plant only.",
      corporateTitle: "Group KPI's",
      corporateDescription: "Cross-plant view for validated events and open actions.",
      year: "Year",
      month: "Month",
      allMonths: "All months",
      from: "From",
      to: "To",
      apply: "Apply",
      clearDates: "Clear dates",
      currentYear: "Current year",
      help: "Help",
      daysWithoutAccidents: "Days without accidents",
      safetyDaysHelp: "Counter calculated from the latest injury record and the admin baseline date.",
      noInjuryRecord: "No injury record",
      current: "Current",
      currentDays: "current days",
      since: "since",
      record: "Record",
      recordDays: "Record {days} days",
      historicalRecord: "Historical record",
      historicalRecordSince: "Historical record since {date}",
      toBeatRecord: "To beat record",
      groupSafetyDays: "Group safety days",
      daysWithoutAccidentsAcrossPlants: "Days without accidents across all plants",
      bestCurrent: "Best current",
      bestRecord: "Best record",
      environmentDashboardEyebrow: "Environment dashboard",
      environmentDashboardHelp: "Visual overview of monthly environmental indicators for {plant}.",
      updateMonthlyInputs: "Update monthly inputs",
      environmentKpis: "Environment KPIs",
      energyConsumption: "Energy consumption",
      waterUsage: "Water usage",
      waste: "Waste",
      spills: "Spills",
      card: "Card",
      line: "Line",
      table: "Table",
      customize: "Customize",
      reset: "Reset",
      moveUp: "Move up",
      moveDown: "Move down",
      monthlyTrend: "Monthly trend",
      consumptionSplit: "Consumption split",
      distribution: "Distribution",
      groupView: "Group view",
      intensity: "Intensity",
      lastInputs: "Last inputs",
      inputs: "Inputs",
      capturedWater: "Captured water",
      operationalHours: "Operational hours",
      environmentalPulse: "Environmental pulse",
      waterProfile: "Water profile",
      wasteByType: "Waste by type",
      operationalContext: "Operational context",
      recentMonthlySnapshot: "Recent monthly snapshot",
      energyProfile: "Energy profile",
      reportingCoverage: "Reporting coverage",
      waterReuseSignal: "Water reuse signal",
      resourceLoad: "Resource load",
      plantComparison: "Plant comparison",
      networkWater: "Network water",
      nonHazardous: "Non-hazardous",
      hazardous: "Hazardous",
      recycled: "Recycled",
      other: "Other",
      noMonthlyInputData: "No monthly input data yet.",
      noDataForThisPeriod: "No data for this period.",
      noPlantDataForThisPeriod: "No plant data for this period.",
      noMonthlyRows: "No monthly rows to show.",
      avgWorkers: "Avg. workers",
      standardHours: "Standard hours",
      selfProducedEnergy: "Self-produced energy",
      recycledWasteShare: "Recycled waste share",
      energyPerWorker: "Energy per worker",
      energyPerStandardHour: "Energy per standard h",
      waterPerWorker: "Water per worker",
      waterPerStandardHour: "Water per standard h",
      wastePerWorker: "Waste per worker",
      wastePerStandardHour: "Waste per standard h",
      plant: "Plant",
      gridElectricity: "Grid electricity",
      selfProducedElectricity: "Self-produced electricity",
      compressedAir: "Compressed air",
      grid: "Grid",
      selfProduced: "Self-produced",
      heating: "Heating",
      monthsWithInputs: "Months with inputs",
      latestMonth: "Latest {month}:",
      noMonthlyData: "No monthly data",
      comparedWithMonthYear: "Compared with {month}/{year}",
      noPreviousYearData: "No previous-year data",
      previousYearSameMonth: "Previous year same month:",
      previousYearSamePeriod: "Previous year same period:",
      comparedWithSameMonthLastYear: "Compared with the same month last year",
      comparedWithSamePeriodLastYear: "Compared with the same period last year",
      pyramidFatal: "Fatal",
      pyramidSeriousInjury: "Serious Injury",
      pyramidMinorInjury: "Minor Injury",
      pyramidFirstAid: "First Aid",
      pyramidNearMiss: "Near Miss",
      pyramidUnsafeCondition: "Unsafe Condition",
      pyramidUnsafeAct: "Unsafe Act",
      language: "Language",
      period: "Period",
      validatedEvents: "Validated events",
      hoursWorked: "Hours worked",
      overdueActions: "Overdue actions",
      myOpenActions: "My open actions",
      openCommunications: "Open communications",
      pendingValidation: "Pending validation",
      clinicalCases: "Clinical cases",
      openActions: "Open actions",
      closedActions: "Closed actions",
      actionsToClose: "Actions to close",
      closedActionsPercent: "% closed actions",
      actionsToClosePercent: "% actions to close",
      nearMisses: "Near misses",
      injuries: "Injuries",
      sewoRootCauses: "S-EWO root causes",
      rootCauseTopFive: "Top 5 root causes",
      rootCauseTotal: "Total",
      noRootCauses: "No root causes identified in this period.",
      frequencyRate: "Frequency rate",
      gravityRate: "Gravity rate",
      safetyCommunicationPyramid: "Safety Communication Pyramid",
      communicationPyramid: "Communication Pyramid",
      plantIndicators: "Plant Indicators",
      corporateIndicators: "Corporate Indicators",
      favoriteIndicators: "Favorite indicators",
      topRankings: "Top rankings",
      scope: "Scope",
      globalScope: "Global",
      plants: "Plants",
      createPlant: "Create plant",
      open: "Open",
      showMore: "Show more",
      showLess: "Show less",
      visualAnalysis: "Visual analysis",
      visualAnalysisDescription: "Trend charts use monthly history; Circular and Pareto use the selected period distribution.",
      comparePlants: "Compare plants",
      indicator: "Indicator",
      value: "Value",
      topRanking: "Top ranking",
      noDataForPeriod: "No data for the selected period.",
      bars: "Bars",
      circular: "Circular",
      points: "Points",
      pareto: "Pareto",
      total: "Total",
      max: "Max",
      backToPlant: "Back to {plant}",
      openReportHistory: "Open report history",
      workersInvolvedRanking: "Workers involved in communications",
      workersReportingRanking: "Workers with more communications submitted",
      departmentsInvolvedRanking: "Departments involved in communications",
      departmentsReportingRanking: "Departments with more communications submitted",
      locationsInvolvedRanking: "Workstations with more communications",
      higherNearMisses: "Higher number of near misses",
      lowerNearMisses: "Lower number of near misses",
      higherInjuries: "Higher number of injuries",
      lowerInjuries: "Lower number of injuries",
      higherFrequencyRate: "Higher frequency rate",
      lowerFrequencyRate: "Lower frequency rate",
      higherGravityRate: "Higher gravity rate",
      lowerGravityRate: "Lower gravity rate",
      actionsRanking: "Actions",
      moreActionsToClose: "More actions to close",
      moreClosedActions: "More closed actions",
      corporatePlants: "Corporate plants",
      selectedPeriodPyramidDescription: "Only one pyramid is shown here, always recalculated for the selected period.",
      plantPyramidDescription: "Communication totals for this plant only.",
      corporatePyramidDescription:
        "Global communication totals are shown by default. Hover a plant to preview the same pyramid for that plant.",
      globalRepeatabilityAlerts: "Global repeatability alerts",
      globalRepeatabilityAlertsDescription:
        "Define the default weekly alert thresholds for all plants. Plant admins can still override these values locally.",
      workerWeeklyRecurrenceLevel1: "Worker weekly recurrence - Level 1",
      workerWeeklyRecurrenceLevel1Description:
        "Trigger when the same involved worker appears more than this number during the same week.",
      workerWeeklyRecurrenceLevel2: "Worker weekly recurrence - Level 2",
      workerWeeklyRecurrenceLevel2Description:
        "Escalation threshold for the same involved worker during the same week.",
      workstationNearMissRecurrence: "Workstation near miss recurrence",
      workstationNearMissRecurrenceDescription:
        "Trigger when the same workstation appears more than this number in near miss records during the same week.",
      enabled: "Enabled",
      saveRepeatabilityAlerts: "Save repeatability alerts",
      repeatabilityAlertsSaved: "Repeatability alerts saved",
      errorSavingRepeatabilityAlerts: "Error saving repeatability alerts",
      repeatabilityAlerts: "Repeatability alerts",
      plantRepeatabilityAlertsDescription:
        "Configure weekly alerts for repeated unsafe acts, first aid, near miss by worker, plus repeated near miss by workstation. These settings apply to this plant and can override the global defaults.",
      recipientLists: "Recipient lists",
      recipients: "recipients",
      alertRules: "Alert rules",
      threshold: "threshold",
      days: "days",
      userManagementUnavailable: "User management is available only for N1 and N3 roles.",
    },
  },
  pt: {
    modules: {
      safetyDashboard: "Dashboard de Segurança",
      environmentDashboard: "Dashboard de Ambiente",
      validation: "Validação",
      communications: "Comunicações",
      actions: "Ações",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Inputs Mensais",
      contractors: "Contratados",
      occupationalHealth: "Medicina do Trabalho",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "KPI's do Grupo",
      settings: "Definições",
    },
    dashboard: {
      plantTitle: "Dashboard de Segurança",
      plantDescription: "Todos os indicadores reagem ao período selecionado e resumem apenas esta planta.",
      corporateTitle: "KPI's do Grupo",
      corporateDescription: "Vista transversal entre plantas para eventos validados e ações abertas.",
      year: "Ano",
      month: "Mês",
      allMonths: "Todos os meses",
      from: "De",
      to: "Até",
      apply: "Aplicar",
      clearDates: "Limpar datas",
      currentYear: "Ano atual",
      help: "Ajuda",
      daysWithoutAccidents: "Dias sem acidentes",
      safetyDaysHelp: "Contador calculado a partir do registo de lesão mais recente e da data base definida na administração.",
      noInjuryRecord: "Sem registo de lesão",
      current: "Atual",
      currentDays: "dias atuais",
      since: "desde",
      record: "Recorde",
      recordDays: "Recorde {days} dias",
      historicalRecord: "Recorde histórico",
      historicalRecordSince: "Recorde histórico desde {date}",
      toBeatRecord: "Para bater o recorde",
      groupSafetyDays: "Dias de segurança do grupo",
      daysWithoutAccidentsAcrossPlants: "Dias sem acidentes em todas as plantas",
      bestCurrent: "Melhor atual",
      bestRecord: "Melhor recorde",
      environmentDashboardEyebrow: "Dashboard de ambiente",
      environmentDashboardHelp: "Visão geral dos indicadores ambientais mensais de {plant}.",
      updateMonthlyInputs: "Atualizar inputs mensais",
      environmentKpis: "KPIs de ambiente",
      energyConsumption: "Consumo de energia",
      waterUsage: "Consumo de água",
      waste: "Resíduos",
      spills: "Derrames",
      card: "Cartão",
      line: "Linha",
      table: "Tabela",
      customize: "Personalizar",
      reset: "Repor",
      moveUp: "Mover para cima",
      moveDown: "Mover para baixo",
      monthlyTrend: "Tendência mensal",
      consumptionSplit: "Divisão do consumo",
      distribution: "Distribuição",
      groupView: "Vista de grupo",
      intensity: "Intensidade",
      lastInputs: "Últimos inputs",
      inputs: "Inputs",
      capturedWater: "Água captada",
      operationalHours: "Horas operacionais",
      environmentalPulse: "Pulso ambiental",
      waterProfile: "Perfil da água",
      wasteByType: "Resíduos por tipo",
      operationalContext: "Contexto operacional",
      recentMonthlySnapshot: "Resumo mensal recente",
      energyProfile: "Perfil energético",
      reportingCoverage: "Cobertura de reporte",
      waterReuseSignal: "Sinal de reutilização de água",
      resourceLoad: "Carga de recursos",
      plantComparison: "Comparação de plantas",
      networkWater: "Água da rede",
      nonHazardous: "Não perigosos",
      hazardous: "Perigosos",
      recycled: "Reciclados",
      other: "Outro",
      noMonthlyInputData: "Ainda não existem inputs mensais.",
      noDataForThisPeriod: "Sem dados para este período.",
      noPlantDataForThisPeriod: "Sem dados de plantas para este período.",
      noMonthlyRows: "Sem linhas mensais para mostrar.",
      avgWorkers: "Média de trabalhadores",
      standardHours: "Horas padrão",
      selfProducedEnergy: "Energia autoproduzida",
      recycledWasteShare: "Percentagem de resíduos reciclados",
      energyPerWorker: "Energia por trabalhador",
      energyPerStandardHour: "Energia por hora padrão",
      waterPerWorker: "Água por trabalhador",
      waterPerStandardHour: "Água por hora padrão",
      wastePerWorker: "Resíduos por trabalhador",
      wastePerStandardHour: "Resíduos por hora padrão",
      plant: "Planta",
      gridElectricity: "Eletricidade da rede",
      selfProducedElectricity: "Eletricidade autoproduzida",
      compressedAir: "Ar comprimido",
      grid: "Rede",
      selfProduced: "Autoproduzida",
      heating: "Aquecimento",
      monthsWithInputs: "Meses com inputs",
      latestMonth: "Último {month}:",
      noMonthlyData: "Sem dados mensais",
      comparedWithMonthYear: "Comparado com {month}/{year}",
      noPreviousYearData: "Sem dados do ano anterior",
      previousYearSameMonth: "Mesmo mês do ano anterior:",
      previousYearSamePeriod: "Mesmo período do ano anterior:",
      comparedWithSameMonthLastYear: "Comparado com o mesmo mês do ano anterior",
      comparedWithSamePeriodLastYear: "Comparado com o mesmo período do ano anterior",
      pyramidFatal: "Fatal",
      pyramidSeriousInjury: "Lesão grave",
      pyramidMinorInjury: "Lesão ligeira",
      pyramidFirstAid: "Primeiros socorros",
      pyramidNearMiss: "Quase acidente",
      pyramidUnsafeCondition: "Condição perigosa",
      pyramidUnsafeAct: "Ato inseguro",
      language: "Idioma",
      period: "Período",
      validatedEvents: "Eventos validados",
      hoursWorked: "Horas trabalhadas",
      overdueActions: "Ações em atraso",
      myOpenActions: "As minhas ações abertas",
      openCommunications: "Comunicações abertas",
      pendingValidation: "Validações pendentes",
      clinicalCases: "Casos clínicos",
      openActions: "Ações abertas",
      closedActions: "Ações fechadas",
      actionsToClose: "Ações por fechar",
      closedActionsPercent: "% de ações fechadas",
      actionsToClosePercent: "% de ações por fechar",
      nearMisses: "Quase acidentes",
      injuries: "Acidentes com lesão",
      sewoRootCauses: "Causas raiz S-EWO",
      rootCauseTopFive: "Top 5 causas raiz",
      rootCauseTotal: "Total",
      noRootCauses: "Sem causas raiz identificadas neste período.",
      frequencyRate: "Índice de frequência",
      gravityRate: "Índice de gravidade",
      safetyCommunicationPyramid: "Pirâmide de Comunicações de Segurança",
      communicationPyramid: "Pirâmide de Comunicações",
      plantIndicators: "Indicadores da Planta",
      corporateIndicators: "Indicadores Corporativos",
      favoriteIndicators: "Indicadores favoritos",
      topRankings: "Rankings principais",
      scope: "Âmbito",
      globalScope: "Global",
      plants: "Plantas",
      createPlant: "Criar planta",
      open: "Abrir",
      showMore: "Mostrar mais",
      showLess: "Mostrar menos",
      visualAnalysis: "Análise visual",
      visualAnalysisDescription: "Os gráficos de tendência usam o histórico mensal; Circular e Pareto usam a distribuição do período selecionado.",
      comparePlants: "Comparar plantas",
      indicator: "Indicador",
      value: "Valor",
      topRanking: "Ranking principal",
      noDataForPeriod: "Sem dados para o período selecionado.",
      bars: "Barras",
      circular: "Circular",
      points: "Pontos",
      pareto: "Pareto",
      total: "Total",
      max: "Máx.",
      backToPlant: "Voltar para {plant}",
      openReportHistory: "Abrir histórico de relatórios",
      workersInvolvedRanking: "Trabalhadores envolvidos em comunicações",
      workersReportingRanking: "Trabalhadores com mais comunicações submetidas",
      departmentsInvolvedRanking: "Departamentos envolvidos em comunicações",
      departmentsReportingRanking: "Departamentos com mais comunicações submetidas",
      locationsInvolvedRanking: "Postos de trabalho com mais comunicações",
      higherNearMisses: "Maior número de quase acidentes",
      lowerNearMisses: "Menor número de quase acidentes",
      higherInjuries: "Maior número de acidentes com lesão",
      lowerInjuries: "Menor número de acidentes com lesão",
      higherFrequencyRate: "Maior índice de frequência",
      lowerFrequencyRate: "Menor índice de frequência",
      higherGravityRate: "Maior índice de gravidade",
      lowerGravityRate: "Menor índice de gravidade",
      actionsRanking: "Ações",
      moreActionsToClose: "Mais ações por fechar",
      moreClosedActions: "Mais ações fechadas",
      corporatePlants: "Plantas corporativas",
      selectedPeriodPyramidDescription: "É apresentada apenas uma pirâmide, sempre recalculada para o período selecionado.",
      plantPyramidDescription: "Totais de comunicações apenas desta planta.",
      corporatePyramidDescription:
        "Por defeito, são apresentados os totais globais de comunicações. Passe sobre uma planta para pré-visualizar a mesma pirâmide dessa planta.",
      globalRepeatabilityAlerts: "Alertas globais de repetibilidade",
      globalRepeatabilityAlertsDescription:
        "Define os limites padrão dos alertas semanais para todas as plantas. Os administradores da planta podem substituir estes valores localmente.",
      workerWeeklyRecurrenceLevel1: "Recorrência semanal por trabalhador - Nível 1",
      workerWeeklyRecurrenceLevel1Description:
        "Gera alerta quando o mesmo trabalhador envolvido aparece mais do que este número durante a mesma semana.",
      workerWeeklyRecurrenceLevel2: "Recorrência semanal por trabalhador - Nível 2",
      workerWeeklyRecurrenceLevel2Description:
        "Limite de escalonamento para o mesmo trabalhador envolvido durante a mesma semana.",
      workstationNearMissRecurrence: "Recorrência semanal de quase acidentes por posto de trabalho",
      workstationNearMissRecurrenceDescription:
        "Gera alerta quando o mesmo posto de trabalho aparece mais do que este número em registos de quase acidente durante a mesma semana.",
      enabled: "Ativo",
      saveRepeatabilityAlerts: "Guardar alertas de repetibilidade",
      repeatabilityAlertsSaved: "Alertas de repetibilidade guardados",
      errorSavingRepeatabilityAlerts: "Erro ao guardar alertas de repetibilidade",
      repeatabilityAlerts: "Alertas de repetibilidade",
      plantRepeatabilityAlertsDescription:
        "Configure alertas semanais para atos inseguros repetidos, primeiros socorros e quase acidentes por trabalhador, além de quase acidentes repetidos por posto de trabalho. Estas definições aplicam-se a esta planta e podem substituir os valores globais.",
      recipientLists: "Listas de destinatários",
      recipients: "destinatários",
      alertRules: "Regras de alerta",
      threshold: "limite",
      days: "dias",
      userManagementUnavailable: "A gestão de utilizadores está disponível apenas para funções N1 e N3.",
    },
  },
  it: {
    modules: {
      safetyDashboard: "Dashboard Sicurezza",
      environmentDashboard: "Dashboard Ambiente",
      validation: "Validazione",
      communications: "Comunicazioni",
      actions: "Azioni",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Input Mensili",
      contractors: "Appaltatori",
      occupationalHealth: "Medicina del Lavoro",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "KPI di Gruppo",
      settings: "Impostazioni",
    },
    dashboard: {
      plantTitle: "Dashboard Sicurezza",
      plantDescription: "Tutti gli indicatori reagiscono al periodo selezionato e riassumono solo questo stabilimento.",
      corporateTitle: "KPI di Gruppo",
      corporateDescription: "Vista trasversale tra stabilimenti per eventi validati e azioni aperte.",
      year: "Anno",
      month: "Mese",
      allMonths: "Tutti i mesi",
      from: "Da",
      to: "A",
      apply: "Applica",
      clearDates: "Cancella date",
      currentYear: "Anno corrente",
      language: "Lingua",
      period: "Periodo",
      validatedEvents: "Eventi validati",
      hoursWorked: "Ore lavorate",
      overdueActions: "Azioni in ritardo",
      myOpenActions: "Le mie azioni aperte",
      openCommunications: "Comunicazioni aperte",
      pendingValidation: "Validazioni in sospeso",
      clinicalCases: "Casi clinici",
      openActions: "Azioni aperte",
      closedActions: "Azioni chiuse",
      actionsToClose: "Azioni da chiudere",
      closedActionsPercent: "% azioni chiuse",
      actionsToClosePercent: "% azioni da chiudere",
      nearMisses: "Near miss",
      injuries: "Infortuni",
      sewoRootCauses: "Cause radice S-EWO",
      rootCauseTopFive: "Top 5 cause radice",
      rootCauseTotal: "Totale",
      noRootCauses: "Nessuna causa radice identificata nel periodo.",
      frequencyRate: "Indice di frequenza",
      gravityRate: "Indice di gravità",
      safetyCommunicationPyramid: "Piramide delle Comunicazioni di Sicurezza",
      communicationPyramid: "Piramide delle Comunicazioni",
      plantIndicators: "Indicatori dello Stabilimento",
      corporateIndicators: "Indicatori Corporate",
      favoriteIndicators: "Indicatori preferiti",
      topRankings: "Ranking principali",
      scope: "Ambito",
      globalScope: "Globale",
      plants: "Stabilimenti",
      createPlant: "Crea stabilimento",
      open: "Apri",
      showMore: "Mostra altro",
      showLess: "Mostra meno",
      visualAnalysis: "Analisi visiva",
      visualAnalysisDescription: "I grafici di tendenza usano lo storico mensile; Circolare e Pareto usano la distribuzione del periodo selezionato.",
      comparePlants: "Confronta stabilimenti",
      indicator: "Indicatore",
      topRanking: "Ranking principale",
      noDataForPeriod: "Nessun dato per il periodo selezionato.",
      bars: "Barre",
      circular: "Circolare",
      points: "Punti",
      pareto: "Pareto",
      total: "Totale",
      max: "Max",
      backToPlant: "Torna a {plant}",
      openReportHistory: "Apri cronologia report",
      workersInvolvedRanking: "Lavoratori coinvolti nelle comunicazioni",
      workersReportingRanking: "Lavoratori con più comunicazioni inviate",
      departmentsInvolvedRanking: "Reparti coinvolti nelle comunicazioni",
      departmentsReportingRanking: "Reparti con più comunicazioni inviate",
      locationsInvolvedRanking: "Postazioni con più comunicazioni",
      higherNearMisses: "Numero maggiore di near miss",
      lowerNearMisses: "Numero minore di near miss",
      higherInjuries: "Numero maggiore di infortuni",
      lowerInjuries: "Numero minore di infortuni",
      higherFrequencyRate: "Indice di frequenza più alto",
      lowerFrequencyRate: "Indice di frequenza più basso",
      higherGravityRate: "Indice di gravità più alto",
      lowerGravityRate: "Indice di gravità più basso",
      actionsRanking: "Azioni",
      moreActionsToClose: "Più azioni da chiudere",
      moreClosedActions: "Più azioni chiuse",
      corporatePlants: "Stabilimenti corporate",
      selectedPeriodPyramidDescription: "Qui viene mostrata una sola piramide, sempre ricalcolata per il periodo selezionato.",
      plantPyramidDescription: "Totali delle comunicazioni solo per questo stabilimento.",
      corporatePyramidDescription:
        "Per impostazione predefinita sono mostrati i totali globali delle comunicazioni. Passa su uno stabilimento per visualizzare la stessa piramide per quello stabilimento.",
      globalRepeatabilityAlerts: "Avvisi globali di ripetibilità",
      globalRepeatabilityAlertsDescription:
        "Definisci le soglie predefinite degli avvisi settimanali per tutti gli stabilimenti. Gli amministratori di stabilimento possono comunque sovrascrivere questi valori localmente.",
      workerWeeklyRecurrenceLevel1: "Ricorrenza settimanale per lavoratore - Livello 1",
      workerWeeklyRecurrenceLevel1Description:
        "Genera un avviso quando lo stesso lavoratore coinvolto compare più di questo numero durante la stessa settimana.",
      workerWeeklyRecurrenceLevel2: "Ricorrenza settimanale per lavoratore - Livello 2",
      workerWeeklyRecurrenceLevel2Description:
        "Soglia di escalation per lo stesso lavoratore coinvolto durante la stessa settimana.",
      workstationNearMissRecurrence: "Ricorrenza dei near miss per postazione",
      workstationNearMissRecurrenceDescription:
        "Genera un avviso quando la stessa postazione compare più di questo numero nei near miss durante la stessa settimana.",
      enabled: "Attivo",
      saveRepeatabilityAlerts: "Salva avvisi di ripetibilità",
      repeatabilityAlertsSaved: "Avvisi di ripetibilità salvati",
      errorSavingRepeatabilityAlerts: "Errore durante il salvataggio degli avvisi di ripetibilità",
      repeatabilityAlerts: "Avvisi di ripetibilità",
      plantRepeatabilityAlertsDescription:
        "Configura gli avvisi settimanali per atti insicuri ripetuti, primo soccorso e near miss per lavoratore, oltre ai near miss ripetuti per postazione. Queste impostazioni si applicano a questo stabilimento e possono sovrascrivere i valori globali.",
      recipientLists: "Liste destinatari",
      recipients: "destinatari",
      alertRules: "Regole di avviso",
      threshold: "soglia",
      days: "giorni",
      userManagementUnavailable: "La gestione utenti è disponibile solo per i ruoli N1 e N3.",
    },
  },
  pl: {
    modules: {
      safetyDashboard: "Panel Bezpieczeństwa",
      environmentDashboard: "Panel Środowiskowy",
      validation: "Walidacja",
      communications: "Zgłoszenia",
      actions: "Działania",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Dane Miesięczne",
      contractors: "Podwykonawcy",
      occupationalHealth: "Medycyna Pracy",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "KPI Grupy",
      settings: "Ustawienia",
    },
    dashboard: {
      plantTitle: "Panel Bezpieczeństwa",
      plantDescription: "Wszystkie wskaźniki reagują na wybrany okres i pokazują tylko ten zakład.",
      corporateTitle: "KPI Grupy",
      corporateDescription: "Widok między zakładami dla zatwierdzonych zdarzeń i otwartych działań.",
      year: "Rok",
      month: "Miesiąc",
      allMonths: "Wszystkie miesiące",
      from: "Od",
      to: "Do",
      apply: "Zastosuj",
      clearDates: "Wyczyść daty",
      currentYear: "Bieżący rok",
      language: "Język",
      period: "Okres",
      validatedEvents: "Zatwierdzone zdarzenia",
      hoursWorked: "Przepracowane godziny",
      overdueActions: "Działania po terminie",
      myOpenActions: "Moje otwarte działania",
      openCommunications: "Otwarte zgłoszenia",
      pendingValidation: "Oczekujące walidacje",
      clinicalCases: "Przypadki kliniczne",
      openActions: "Otwarte działania",
      closedActions: "Zamknięte działania",
      actionsToClose: "Działania do zamknięcia",
      closedActionsPercent: "% zamkniętych działań",
      actionsToClosePercent: "% działań do zamknięcia",
      nearMisses: "Zdarzenia potencjalnie wypadkowe",
      injuries: "Urazy",
      sewoRootCauses: "Przyczyny źródłowe S-EWO",
      rootCauseTopFive: "Top 5 przyczyn źródłowych",
      rootCauseTotal: "Razem",
      noRootCauses: "Brak zidentyfikowanych przyczyn źródłowych w tym okresie.",
      frequencyRate: "Wskaźnik częstości",
      gravityRate: "Wskaźnik ciężkości",
      safetyCommunicationPyramid: "Piramida Komunikacji Bezpieczeństwa",
      communicationPyramid: "Piramida Komunikacji",
      plantIndicators: "Wskaźniki Zakładu",
      corporateIndicators: "Wskaźniki Korporacyjne",
      favoriteIndicators: "Ulubione wskaźniki",
      topRankings: "Główne rankingi",
      scope: "Zakres",
      globalScope: "Globalnie",
      plants: "Zakłady",
      createPlant: "Utwórz zakład",
      open: "Otwórz",
      showMore: "Pokaż więcej",
      showLess: "Pokaż mniej",
      visualAnalysis: "Analiza wizualna",
      visualAnalysisDescription: "Wykresy trendów używają historii miesięcznej; wykres kołowy i Pareto używają rozkładu z wybranego okresu.",
      comparePlants: "Porównaj zakłady",
      indicator: "Wskaźnik",
      topRanking: "Główny ranking",
      noDataForPeriod: "Brak danych dla wybranego okresu.",
      bars: "Słupki",
      circular: "Kołowy",
      points: "Punkty",
      pareto: "Pareto",
      total: "Razem",
      max: "Maks.",
      backToPlant: "Wróć do {plant}",
      openReportHistory: "Otwórz historię raportów",
      workersInvolvedRanking: "Pracownicy uczestniczący w zgłoszeniach",
      workersReportingRanking: "Pracownicy z największą liczbą wysłanych zgłoszeń",
      departmentsInvolvedRanking: "Działy uczestniczące w zgłoszeniach",
      departmentsReportingRanking: "Działy z największą liczbą wysłanych zgłoszeń",
      locationsInvolvedRanking: "Stanowiska z największą liczbą zgłoszeń",
      higherNearMisses: "Najwięcej zdarzeń potencjalnie wypadkowych",
      lowerNearMisses: "Najmniej zdarzeń potencjalnie wypadkowych",
      higherInjuries: "Najwięcej urazów",
      lowerInjuries: "Najmniej urazów",
      higherFrequencyRate: "Najwyższy wskaźnik częstotliwości",
      lowerFrequencyRate: "Najniższy wskaźnik częstotliwości",
      higherGravityRate: "Najwyższy wskaźnik ciężkości",
      lowerGravityRate: "Najniższy wskaźnik ciężkości",
      actionsRanking: "Działania",
      moreActionsToClose: "Więcej działań do zamknięcia",
      moreClosedActions: "Więcej zamkniętych działań",
      corporatePlants: "Zakłady korporacyjne",
      selectedPeriodPyramidDescription: "Wyświetlana jest tutaj tylko jedna piramida, zawsze przeliczana dla wybranego okresu.",
      plantPyramidDescription: "Sumy zgłoszeń tylko dla tego zakładu.",
      corporatePyramidDescription:
        "Domyślnie wyświetlane są globalne sumy zgłoszeń. Najedź na zakład, aby zobaczyć tę samą piramidę dla tego zakładu.",
      globalRepeatabilityAlerts: "Globalne alerty powtarzalności",
      globalRepeatabilityAlertsDescription:
        "Zdefiniuj domyślne tygodniowe progi alertów dla wszystkich zakładów. Administratorzy zakładów nadal mogą nadpisać te wartości lokalnie.",
      workerWeeklyRecurrenceLevel1: "Tygodniowa powtarzalność pracownika - Poziom 1",
      workerWeeklyRecurrenceLevel1Description:
        "Wyzwala alert, gdy ten sam pracownik uczestniczący pojawia się częściej niż ta liczba w tym samym tygodniu.",
      workerWeeklyRecurrenceLevel2: "Tygodniowa powtarzalność pracownika - Poziom 2",
      workerWeeklyRecurrenceLevel2Description:
        "Próg eskalacji dla tego samego pracownika uczestniczącego w tym samym tygodniu.",
      workstationNearMissRecurrence: "Powtarzalność zdarzeń potencjalnie wypadkowych na stanowisku",
      workstationNearMissRecurrenceDescription:
        "Wyzwala alert, gdy to samo stanowisko pojawia się częściej niż ta liczba w zgłoszeniach zdarzeń potencjalnie wypadkowych w tym samym tygodniu.",
      enabled: "Aktywne",
      saveRepeatabilityAlerts: "Zapisz alerty powtarzalności",
      repeatabilityAlertsSaved: "Alerty powtarzalności zapisane",
      errorSavingRepeatabilityAlerts: "Błąd podczas zapisywania alertów powtarzalności",
      repeatabilityAlerts: "Alerty powtarzalności",
      plantRepeatabilityAlertsDescription:
        "Skonfiguruj tygodniowe alerty dla powtarzających się niebezpiecznych zachowań, pierwszej pomocy i zdarzeń potencjalnie wypadkowych według pracownika oraz powtarzających się zdarzeń potencjalnie wypadkowych według stanowiska. Te ustawienia dotyczą tego zakładu i mogą nadpisać wartości globalne.",
      recipientLists: "Listy odbiorców",
      recipients: "odbiorców",
      alertRules: "Reguły alertów",
      threshold: "próg",
      days: "dni",
      userManagementUnavailable: "Zarządzanie użytkownikami jest dostępne tylko dla ról N1 i N3.",
    },
  },
  de: {
    modules: {
      safetyDashboard: "Sicherheits-Dashboard",
      environmentDashboard: "Umwelt-Dashboard",
      validation: "Validierung",
      communications: "Meldungen",
      actions: "Maßnahmen",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Monatliche Eingaben",
      contractors: "Fremdfirmen",
      occupationalHealth: "Arbeitsmedizin",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Gruppen-KPI",
      settings: "Einstellungen",
    },
    dashboard: {
      plantTitle: "Sicherheits-Dashboard",
      plantDescription: "Alle Kennzahlen reagieren auf den gewählten Zeitraum und beziehen sich nur auf dieses Werk.",
      corporateTitle: "Gruppen-KPI",
      corporateDescription: "Werkübergreifende Sicht auf validierte Ereignisse und offene Maßnahmen.",
      year: "Jahr",
      month: "Monat",
      allMonths: "Alle Monate",
      from: "Von",
      to: "Bis",
      apply: "Anwenden",
      clearDates: "Daten löschen",
      currentYear: "Aktuelles Jahr",
      language: "Sprache",
      period: "Zeitraum",
      validatedEvents: "Validierte Ereignisse",
      hoursWorked: "Geleistete Arbeitsstunden",
      overdueActions: "Überfällige Maßnahmen",
      myOpenActions: "Meine offenen Maßnahmen",
      openCommunications: "Offene Meldungen",
      pendingValidation: "Ausstehende Validierungen",
      clinicalCases: "Klinische Fälle",
      openActions: "Offene Maßnahmen",
      closedActions: "Geschlossene Maßnahmen",
      actionsToClose: "Zu schließende Maßnahmen",
      closedActionsPercent: "% geschlossene Maßnahmen",
      actionsToClosePercent: "% zu schließende Maßnahmen",
      nearMisses: "Beinaheunfälle",
      injuries: "Verletzungen",
      sewoRootCauses: "S-EWO-Grundursachen",
      rootCauseTopFive: "Top 5 Grundursachen",
      rootCauseTotal: "Gesamt",
      noRootCauses: "In diesem Zeitraum wurden keine Grundursachen identifiziert.",
      frequencyRate: "Häufigkeitsrate",
      gravityRate: "Schweregradrate",
      safetyCommunicationPyramid: "Pyramide der Sicherheitsmeldungen",
      communicationPyramid: "Meldungspyramide",
      plantIndicators: "Werkskennzahlen",
      corporateIndicators: "Konzernkennzahlen",
      favoriteIndicators: "Favorisierte Kennzahlen",
      topRankings: "Top-Rankings",
      scope: "Umfang",
      globalScope: "Global",
      plants: "Werke",
      createPlant: "Werk erstellen",
      open: "Öffnen",
      showMore: "Mehr anzeigen",
      showLess: "Weniger anzeigen",
      visualAnalysis: "Visuelle Analyse",
      visualAnalysisDescription: "Trenddiagramme nutzen die monatliche Historie; Kreis- und Pareto-Diagramme nutzen die Verteilung des ausgewählten Zeitraums.",
      comparePlants: "Werke vergleichen",
      indicator: "Kennzahl",
      topRanking: "Top-Ranking",
      noDataForPeriod: "Keine Daten für den ausgewählten Zeitraum.",
      bars: "Balken",
      circular: "Kreis",
      points: "Punkte",
      pareto: "Pareto",
      total: "Gesamt",
      max: "Max.",
      backToPlant: "Zurück zu {plant}",
      openReportHistory: "Berichtshistorie öffnen",
      workersInvolvedRanking: "An Meldungen beteiligte Mitarbeitende",
      workersReportingRanking: "Mitarbeitende mit den meisten eingereichten Meldungen",
      departmentsInvolvedRanking: "An Meldungen beteiligte Abteilungen",
      departmentsReportingRanking: "Abteilungen mit den meisten eingereichten Meldungen",
      locationsInvolvedRanking: "Arbeitsplätze mit den meisten Meldungen",
      higherNearMisses: "Höhere Anzahl von Beinaheunfällen",
      lowerNearMisses: "Niedrigere Anzahl von Beinaheunfällen",
      higherInjuries: "Höhere Anzahl von Verletzungen",
      lowerInjuries: "Niedrigere Anzahl von Verletzungen",
      higherFrequencyRate: "Höhere Häufigkeitsrate",
      lowerFrequencyRate: "Niedrigere Häufigkeitsrate",
      higherGravityRate: "Höhere Schweregradrate",
      lowerGravityRate: "Niedrigere Schweregradrate",
      actionsRanking: "Maßnahmen",
      moreActionsToClose: "Mehr zu schließende Maßnahmen",
      moreClosedActions: "Mehr geschlossene Maßnahmen",
      corporatePlants: "Konzernwerke",
      selectedPeriodPyramidDescription: "Hier wird nur eine Pyramide angezeigt, immer neu berechnet für den ausgewählten Zeitraum.",
      plantPyramidDescription: "Meldungssummen nur für dieses Werk.",
      corporatePyramidDescription:
        "Standardmäßig werden die globalen Meldungssummen angezeigt. Bewegen Sie den Mauszeiger über ein Werk, um dieselbe Pyramide für dieses Werk anzuzeigen.",
      globalRepeatabilityAlerts: "Globale Wiederholungswarnungen",
      globalRepeatabilityAlertsDescription:
        "Definiert die wöchentlichen Standardwarnschwellen für alle Werke. Werksadministratoren können diese Werte lokal weiterhin überschreiben.",
      workerWeeklyRecurrenceLevel1: "Wöchentliche Wiederholung je Mitarbeitendem - Stufe 1",
      workerWeeklyRecurrenceLevel1Description:
        "Löst eine Warnung aus, wenn derselbe beteiligte Mitarbeitende in derselben Woche häufiger als dieser Wert erscheint.",
      workerWeeklyRecurrenceLevel2: "Wöchentliche Wiederholung je Mitarbeitendem - Stufe 2",
      workerWeeklyRecurrenceLevel2Description:
        "Eskalationsschwelle für denselben beteiligten Mitarbeitenden in derselben Woche.",
      workstationNearMissRecurrence: "Wiederholung von Beinaheunfällen je Arbeitsplatz",
      workstationNearMissRecurrenceDescription:
        "Löst eine Warnung aus, wenn derselbe Arbeitsplatz in derselben Woche häufiger als dieser Wert in Beinaheunfallmeldungen erscheint.",
      enabled: "Aktiv",
      saveRepeatabilityAlerts: "Wiederholungswarnungen speichern",
      repeatabilityAlertsSaved: "Wiederholungswarnungen gespeichert",
      errorSavingRepeatabilityAlerts: "Fehler beim Speichern der Wiederholungswarnungen",
      repeatabilityAlerts: "Wiederholungswarnungen",
      plantRepeatabilityAlertsDescription:
        "Konfigurieren Sie wöchentliche Warnungen für wiederholte unsichere Handlungen, Erste Hilfe und Beinaheunfälle je Mitarbeitendem sowie wiederholte Beinaheunfälle je Arbeitsplatz. Diese Einstellungen gelten für dieses Werk und können globale Standardwerte überschreiben.",
      recipientLists: "Empfängerlisten",
      recipients: "Empfänger",
      alertRules: "Warnregeln",
      threshold: "Schwellenwert",
      days: "Tage",
      userManagementUnavailable: "Benutzerverwaltung ist nur für N1- und N3-Rollen verfügbar.",
    },
  },
  ro: {
    modules: {
      safetyDashboard: "Tablou de siguranță",
      environmentDashboard: "Tablou de mediu",
      validation: "Validare",
      communications: "Comunicări",
      actions: "Acțiuni",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Date lunare",
      contractors: "Contractori",
      occupationalHealth: "Medicina muncii",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "KPI-uri de grup",
      settings: "Setări",
    },
    dashboard: {
      plantTitle: "Tablou de siguranță",
      plantDescription: "Toți indicatorii reacționează la perioada selectată și rezumă doar această fabrică.",
      corporateTitle: "KPI-uri de grup",
      corporateDescription: "Vedere transversală între fabrici pentru evenimente validate și acțiuni deschise.",
      year: "An",
      month: "Lună",
      allMonths: "Toate lunile",
      from: "De la",
      to: "Până la",
      apply: "Aplică",
      clearDates: "Șterge datele",
      currentYear: "Anul curent",
      language: "Limbă",
      period: "Perioadă",
      validatedEvents: "Evenimente validate",
      hoursWorked: "Ore lucrate",
      overdueActions: "Acțiuni întârziate",
      myOpenActions: "Acțiunile mele deschise",
      openCommunications: "Comunicări deschise",
      pendingValidation: "Validări în așteptare",
      clinicalCases: "Cazuri clinice",
      openActions: "Acțiuni deschise",
      closedActions: "Acțiuni închise",
      actionsToClose: "Acțiuni de închis",
      closedActionsPercent: "% acțiuni închise",
      actionsToClosePercent: "% acțiuni de închis",
      nearMisses: "Evenimente la limită",
      injuries: "Accidentări",
      sewoRootCauses: "Cauze rădăcină S-EWO",
      rootCauseTopFive: "Top 5 cauze rădăcină",
      rootCauseTotal: "Total",
      noRootCauses: "Nu au fost identificate cauze rădăcină în această perioadă.",
      frequencyRate: "Indice de frecvență",
      gravityRate: "Indice de gravitate",
      safetyCommunicationPyramid: "Piramida Comunicării de Siguranță",
      communicationPyramid: "Piramida Comunicării",
      plantIndicators: "Indicatorii fabricii",
      corporateIndicators: "Indicatori corporativi",
      favoriteIndicators: "Indicatori favoriți",
      topRankings: "Clasamente principale",
      scope: "Domeniu",
      globalScope: "Global",
      plants: "Fabrici",
      createPlant: "Creează fabrică",
      open: "Deschide",
      showMore: "Afișează mai mult",
      showLess: "Afișează mai puțin",
      visualAnalysis: "Analiză vizuală",
      visualAnalysisDescription: "Graficele de tendință folosesc istoricul lunar; graficele circulare și Pareto folosesc distribuția perioadei selectate.",
      comparePlants: "Compară fabrici",
      indicator: "Indicator",
      topRanking: "Clasament principal",
      noDataForPeriod: "Nu există date pentru perioada selectată.",
      bars: "Bare",
      circular: "Circular",
      points: "Puncte",
      pareto: "Pareto",
      total: "Total",
      max: "Max.",
      backToPlant: "Înapoi la {plant}",
      openReportHistory: "Deschide istoricul rapoartelor",
      workersInvolvedRanking: "Lucrători implicați în comunicări",
      workersReportingRanking: "Lucrători cu cele mai multe comunicări trimise",
      departmentsInvolvedRanking: "Departamente implicate în comunicări",
      departmentsReportingRanking: "Departamente cu cele mai multe comunicări trimise",
      locationsInvolvedRanking: "Posturi de lucru cu cele mai multe comunicări",
      higherNearMisses: "Număr mai mare de evenimente la limită",
      lowerNearMisses: "Număr mai mic de evenimente la limită",
      higherInjuries: "Număr mai mare de accidentări",
      lowerInjuries: "Număr mai mic de accidentări",
      higherFrequencyRate: "Indice de frecvență mai mare",
      lowerFrequencyRate: "Indice de frecvență mai mic",
      higherGravityRate: "Indice de gravitate mai mare",
      lowerGravityRate: "Indice de gravitate mai mic",
      actionsRanking: "Acțiuni",
      moreActionsToClose: "Mai multe acțiuni de închis",
      moreClosedActions: "Mai multe acțiuni închise",
      corporatePlants: "Fabrici corporate",
      selectedPeriodPyramidDescription: "Aici este afișată o singură piramidă, recalculată întotdeauna pentru perioada selectată.",
      plantPyramidDescription: "Totaluri ale comunicărilor doar pentru această fabrică.",
      corporatePyramidDescription:
        "În mod implicit sunt afișate totalurile globale ale comunicărilor. Treceți peste o fabrică pentru a previzualiza aceeași piramidă pentru fabrica respectivă.",
      globalRepeatabilityAlerts: "Alerte globale de repetabilitate",
      globalRepeatabilityAlertsDescription:
        "Definește pragurile implicite ale alertelor săptămânale pentru toate fabricile. Administratorii fabricilor pot suprascrie local aceste valori.",
      workerWeeklyRecurrenceLevel1: "Recurență săptămânală per lucrător - Nivel 1",
      workerWeeklyRecurrenceLevel1Description:
        "Declanșează o alertă când același lucrător implicat apare de mai multe ori decât acest număr în aceeași săptămână.",
      workerWeeklyRecurrenceLevel2: "Recurență săptămânală per lucrător - Nivel 2",
      workerWeeklyRecurrenceLevel2Description:
        "Prag de escaladare pentru același lucrător implicat în aceeași săptămână.",
      workstationNearMissRecurrence: "Recurență a evenimentelor la limită per post de lucru",
      workstationNearMissRecurrenceDescription:
        "Declanșează o alertă când același post de lucru apare de mai multe ori decât acest număr în evenimente la limită în aceeași săptămână.",
      enabled: "Activ",
      saveRepeatabilityAlerts: "Salvează alertele de repetabilitate",
      repeatabilityAlertsSaved: "Alerte de repetabilitate salvate",
      errorSavingRepeatabilityAlerts: "Eroare la salvarea alertelor de repetabilitate",
      repeatabilityAlerts: "Alerte de repetabilitate",
      plantRepeatabilityAlertsDescription:
        "Configurați alerte săptămânale pentru acte nesigure repetate, prim ajutor și evenimente la limită per lucrător, plus evenimente la limită repetate per post de lucru. Aceste setări se aplică acestei fabrici și pot suprascrie valorile globale.",
      recipientLists: "Liste de destinatari",
      recipients: "destinatari",
      alertRules: "Reguli de alertă",
      threshold: "prag",
      days: "zile",
      userManagementUnavailable: "Gestionarea utilizatorilor este disponibilă doar pentru rolurile N1 și N3.",
    },
  },
  fr: {
    modules: {
      safetyDashboard: "Tableau de sécurité",
      environmentDashboard: "Tableau environnement",
      validation: "Validation",
      communications: "Communications",
      actions: "Actions",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Saisies mensuelles",
      contractors: "Entreprises externes",
      occupationalHealth: "Santé au travail",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "KPI groupe",
      settings: "Paramètres",
    },
    dashboard: {
      plantTitle: "Tableau de sécurité",
      plantDescription: "Tous les indicateurs réagissent à la période sélectionnée et résument uniquement cette usine.",
      corporateTitle: "KPI groupe",
      corporateDescription: "Vue transversale entre usines pour les événements validés et les actions ouvertes.",
      year: "Année",
      month: "Mois",
      allMonths: "Tous les mois",
      from: "De",
      to: "À",
      apply: "Appliquer",
      clearDates: "Effacer les dates",
      currentYear: "Année en cours",
      language: "Langue",
      period: "Période",
      validatedEvents: "Événements validés",
      hoursWorked: "Heures travaillées",
      overdueActions: "Actions en retard",
      myOpenActions: "Mes actions ouvertes",
      openCommunications: "Communications ouvertes",
      pendingValidation: "Validations en attente",
      clinicalCases: "Cas cliniques",
      openActions: "Actions ouvertes",
      closedActions: "Actions clôturées",
      actionsToClose: "Actions à clôturer",
      closedActionsPercent: "% actions clôturées",
      actionsToClosePercent: "% actions à clôturer",
      nearMisses: "Presqu'accidents",
      injuries: "Blessures",
      sewoRootCauses: "Causes racines S-EWO",
      rootCauseTopFive: "Top 5 causes racines",
      rootCauseTotal: "Total",
      noRootCauses: "Aucune cause racine identifiée sur cette période.",
      frequencyRate: "Taux de fréquence",
      gravityRate: "Taux de gravité",
      safetyCommunicationPyramid: "Pyramide des Communications Sécurité",
      communicationPyramid: "Pyramide des Communications",
      plantIndicators: "Indicateurs de l'usine",
      corporateIndicators: "Indicateurs corporate",
      favoriteIndicators: "Indicateurs favoris",
      topRankings: "Classements principaux",
      scope: "Périmètre",
      globalScope: "Global",
      plants: "Usines",
      createPlant: "Créer une usine",
      open: "Ouvrir",
      showMore: "Afficher plus",
      showLess: "Afficher moins",
      visualAnalysis: "Analyse visuelle",
      visualAnalysisDescription: "Les graphiques de tendance utilisent l'historique mensuel ; les graphiques circulaires et Pareto utilisent la distribution de la période sélectionnée.",
      comparePlants: "Comparer les usines",
      indicator: "Indicateur",
      topRanking: "Classement principal",
      noDataForPeriod: "Aucune donnée pour la période sélectionnée.",
      bars: "Barres",
      circular: "Circulaire",
      points: "Points",
      pareto: "Pareto",
      total: "Total",
      max: "Max.",
      backToPlant: "Retour à {plant}",
      openReportHistory: "Ouvrir l'historique des rapports",
      workersInvolvedRanking: "Collaborateurs impliqués dans les communications",
      workersReportingRanking: "Collaborateurs ayant soumis le plus de communications",
      departmentsInvolvedRanking: "Départements impliqués dans les communications",
      departmentsReportingRanking: "Départements ayant soumis le plus de communications",
      locationsInvolvedRanking: "Postes avec le plus de communications",
      higherNearMisses: "Nombre plus élevé de presqu'accidents",
      lowerNearMisses: "Nombre plus faible de presqu'accidents",
      higherInjuries: "Nombre plus élevé de blessures",
      lowerInjuries: "Nombre plus faible de blessures",
      higherFrequencyRate: "Taux de fréquence plus élevé",
      lowerFrequencyRate: "Taux de fréquence plus faible",
      higherGravityRate: "Taux de gravité plus élevé",
      lowerGravityRate: "Taux de gravité plus faible",
      actionsRanking: "Actions",
      moreActionsToClose: "Plus d'actions à clôturer",
      moreClosedActions: "Plus d'actions clôturées",
      corporatePlants: "Usines corporate",
      selectedPeriodPyramidDescription: "Une seule pyramide est affichée ici, toujours recalculée pour la période sélectionnée.",
      plantPyramidDescription: "Totaux des communications pour cette usine uniquement.",
      corporatePyramidDescription:
        "Les totaux globaux des communications sont affichés par défaut. Survolez une usine pour prévisualiser la même pyramide pour cette usine.",
      globalRepeatabilityAlerts: "Alertes globales de répétabilité",
      globalRepeatabilityAlertsDescription:
        "Définit les seuils d'alerte hebdomadaires par défaut pour toutes les usines. Les administrateurs d'usine peuvent toujours remplacer ces valeurs localement.",
      workerWeeklyRecurrenceLevel1: "Récurrence hebdomadaire par collaborateur - Niveau 1",
      workerWeeklyRecurrenceLevel1Description:
        "Déclenche une alerte lorsque le même collaborateur impliqué apparaît plus que ce nombre pendant la même semaine.",
      workerWeeklyRecurrenceLevel2: "Récurrence hebdomadaire par collaborateur - Niveau 2",
      workerWeeklyRecurrenceLevel2Description:
        "Seuil d'escalade pour le même collaborateur impliqué pendant la même semaine.",
      workstationNearMissRecurrence: "Récurrence des presqu'accidents par poste",
      workstationNearMissRecurrenceDescription:
        "Déclenche une alerte lorsque le même poste apparaît plus que ce nombre dans les presqu'accidents pendant la même semaine.",
      enabled: "Actif",
      saveRepeatabilityAlerts: "Enregistrer les alertes de répétabilité",
      repeatabilityAlertsSaved: "Alertes de répétabilité enregistrées",
      errorSavingRepeatabilityAlerts: "Erreur lors de l'enregistrement des alertes de répétabilité",
      repeatabilityAlerts: "Alertes de répétabilité",
      plantRepeatabilityAlertsDescription:
        "Configurez les alertes hebdomadaires pour les actes dangereux répétés, les premiers secours et les presqu'accidents par collaborateur, ainsi que les presqu'accidents répétés par poste. Ces paramètres s'appliquent à cette usine et peuvent remplacer les valeurs globales.",
      recipientLists: "Listes de destinataires",
      recipients: "destinataires",
      alertRules: "Règles d'alerte",
      threshold: "seuil",
      days: "jours",
      userManagementUnavailable: "La gestion des utilisateurs est disponible uniquement pour les rôles N1 et N3.",
    },
  },
} as const;

type WidenDictionary<T> = {
  [Key in keyof T]: T[Key] extends string
    ? string
    : T[Key] extends Record<string, unknown>
      ? WidenDictionary<T[Key]>
      : T[Key];
};

export type UiDictionary = WidenDictionary<(typeof UI_DICTIONARY)["en"]>;
export type DashboardUiDictionary = UiDictionary["dashboard"];

export function normalizeUiLocale(locale: string | null | undefined) {
  return (locale && locale in UI_DICTIONARY ? locale : "en") as keyof typeof UI_DICTIONARY;
}

function isDictionaryRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function mergeWithFallback<T>(fallback: T, selected: unknown): T {
  if (!isDictionaryRecord(fallback)) {
    return (selected ?? fallback) as T;
  }

  if (!isDictionaryRecord(selected)) {
    return fallback;
  }

  const result: Record<string, unknown> = { ...fallback };
  for (const [key, fallbackValue] of Object.entries(fallback)) {
    const selectedValue = selected[key];
    result[key] = isDictionaryRecord(fallbackValue)
      ? mergeWithFallback(fallbackValue, selectedValue)
      : selectedValue ?? fallbackValue;
  }

  return result as T;
}

export function getUiDictionary(locale: string | null | undefined): UiDictionary {
  const normalizedLocale = normalizeUiLocale(locale);
  if (normalizedLocale === "en") {
    return UI_DICTIONARY.en;
  }

  return mergeWithFallback(UI_DICTIONARY.en, UI_DICTIONARY[normalizedLocale]);
}
