import type { AppLocale } from "@/lib/i18n/routing";

export const DASHBOARD_LANGUAGES = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
  { code: "pl", label: "Polski", flag: "🇵🇱" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
] as const satisfies Array<{ code: AppLocale; label: string; flag: string }>;

const UI_DICTIONARY = {
  en: {
    modules: {
      safetyDashboard: "Safety Dashboard",
      environmentDashboard: "Environment Dashboard",
      validation: "Validation",
      communications: "Communications",
      actions: "Actions",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Monthly Inputs",
      contractors: "Contractors",
      occupationalHealth: "Occupational Health",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Group KPI's",
      settings: "Settings",
    },
    dashboard: {
      plantTitle: "Safety Dashboard",
      plantDescription: "All indicators react to the selected period and summarize this plant only.",
      corporateTitle: "Group KPI's",
      corporateDescription: "Cross-plant read-only view for validated events and open actions. Default scope is the full current year.",
      year: "Year",
      month: "Month",
      from: "From",
      to: "To",
      apply: "Apply",
      currentYear: "Current year",
      language: "Language",
    },
  },
  pt: {
    modules: {
      safetyDashboard: "Dashboard de Segurança",
      environmentDashboard: "Dashboard de Ambiente",
      validation: "Validação",
      communications: "Comunicações",
      actions: "Ações",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Inputs Mensais",
      contractors: "Contratados",
      occupationalHealth: "Medicina do Trabalho",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Group KPI's",
      settings: "Definições",
    },
    dashboard: {
      plantTitle: "Dashboard de Segurança",
      plantDescription: "Todos os indicadores reagem ao período selecionado e resumem apenas esta planta.",
      corporateTitle: "Group KPI's",
      corporateDescription: "Vista transversal entre plantas para eventos validados e ações abertas.",
      year: "Ano",
      month: "Mês",
      from: "De",
      to: "Até",
      apply: "Aplicar",
      currentYear: "Ano atual",
      language: "Idioma",
    },
  },
  it: {
    modules: {
      safetyDashboard: "Dashboard Sicurezza",
      environmentDashboard: "Dashboard Ambiente",
      validation: "Validazione",
      communications: "Comunicazioni",
      actions: "Azioni",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Input Mensili",
      contractors: "Appaltatori",
      occupationalHealth: "Medicina del Lavoro",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Group KPI's",
      settings: "Impostazioni",
    },
    dashboard: {
      plantTitle: "Dashboard Sicurezza",
      plantDescription: "Tutti gli indicatori reagiscono al periodo selezionato e riassumono solo questo stabilimento.",
      corporateTitle: "Group KPI's",
      corporateDescription: "Vista trasversale tra stabilimenti per eventi validati e azioni aperte.",
      year: "Anno",
      month: "Mese",
      from: "Da",
      to: "A",
      apply: "Applica",
      currentYear: "Anno corrente",
      language: "Lingua",
    },
  },
  pl: {
    modules: {
      safetyDashboard: "Panel Bezpieczeństwa",
      environmentDashboard: "Panel Środowiskowy",
      validation: "Walidacja",
      communications: "Zgłoszenia",
      actions: "Działania",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Dane Miesięczne",
      contractors: "Podwykonawcy",
      occupationalHealth: "Medycyna Pracy",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Group KPI's",
      settings: "Ustawienia",
    },
    dashboard: {
      plantTitle: "Panel Bezpieczeństwa",
      plantDescription: "Wszystkie wskaźniki reagują na wybrany okres i pokazują tylko tę fabrykę.",
      corporateTitle: "Group KPI's",
      corporateDescription: "Widok między zakładami dla zatwierdzonych zdarzeń i otwartych działań.",
      year: "Rok",
      month: "Miesiąc",
      from: "Od",
      to: "Do",
      apply: "Zastosuj",
      currentYear: "Bieżący rok",
      language: "Język",
    },
  },
  de: {
    modules: {
      safetyDashboard: "Sicherheits-Dashboard",
      environmentDashboard: "Umwelt-Dashboard",
      validation: "Validierung",
      communications: "Meldungen",
      actions: "Maßnahmen",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Monatliche Eingaben",
      contractors: "Fremdfirmen",
      occupationalHealth: "Arbeitsmedizin",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Group KPI's",
      settings: "Einstellungen",
    },
    dashboard: {
      plantTitle: "Sicherheits-Dashboard",
      plantDescription: "Alle Kennzahlen reagieren auf den gewählten Zeitraum und beziehen sich nur auf dieses Werk.",
      corporateTitle: "Group KPI's",
      corporateDescription: "Werksübergreifende Sicht auf validierte Ereignisse und offene Maßnahmen.",
      year: "Jahr",
      month: "Monat",
      from: "Von",
      to: "Bis",
      apply: "Anwenden",
      currentYear: "Aktuelles Jahr",
      language: "Sprache",
    },
  },
  ro: {
    modules: {
      safetyDashboard: "Safety Dashboard",
      environmentDashboard: "Environment Dashboard",
      validation: "Validation",
      communications: "Communications",
      actions: "Actions",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Monthly Inputs",
      contractors: "Contractors",
      occupationalHealth: "Occupational Health",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Group KPI's",
      settings: "Settings",
    },
    dashboard: {
      plantTitle: "Safety Dashboard",
      plantDescription: "All indicators react to the selected period and summarize this plant only.",
      corporateTitle: "Group KPI's",
      corporateDescription: "Cross-plant read-only view for validated events and open actions.",
      year: "Year",
      month: "Month",
      from: "From",
      to: "To",
      apply: "Apply",
      currentYear: "Current year",
      language: "Language",
    },
  },
  fr: {
    modules: {
      safetyDashboard: "Safety Dashboard",
      environmentDashboard: "Environment Dashboard",
      validation: "Validation",
      communications: "Communications",
      actions: "Actions",
      sewo: "S-EWO",
      smat: "SMAT",
      monthlyInputs: "Monthly Inputs",
      contractors: "Contractors",
      occupationalHealth: "Occupational Health",
      mapa: "MAPA",
      admin: "Admin",
      corporate: "Group KPI's",
      settings: "Settings",
    },
    dashboard: {
      plantTitle: "Safety Dashboard",
      plantDescription: "All indicators react to the selected period and summarize this plant only.",
      corporateTitle: "Group KPI's",
      corporateDescription: "Cross-plant read-only view for validated events and open actions.",
      year: "Year",
      month: "Month",
      from: "From",
      to: "To",
      apply: "Apply",
      currentYear: "Current year",
      language: "Language",
    },
  },
} as const;

export function getUiDictionary(locale: string) {
  return UI_DICTIONARY[(locale in UI_DICTIONARY ? locale : "en") as keyof typeof UI_DICTIONARY];
}
